USE OURVLECloneDatabase;
TRUNCATE TABLE Lecturer;

 ──── Lecturers ────────────────────────────────────────────────────────────────────
INSERT INTO Lecturer VALUES ('SOCI1', 'Kellie Mclaughlin', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS2', 'Jeffrey Butler', 'Physics');
INSERT INTO Lecturer VALUES ('MATH3', 'Erika Cline', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG4', 'Sean Randall', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHAR5', 'April Juarez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHAR6', 'Karina Banks', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI7', 'Lauren Garcia', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON8', 'Richard Weaver', 'Economics');
INSERT INTO Lecturer VALUES ('PHYS9', 'Paul Griffin', 'Physics');
INSERT INTO Lecturer VALUES ('CENG10', 'Edward Benjamin', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GOVN11', 'Stephen Lee', 'Government');
INSERT INTO Lecturer VALUES ('ECON12', 'Shane Long PhD', 'Economics');
INSERT INTO Lecturer VALUES ('GEOG13', 'Bobby Stewart', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG14', 'Jessica Stone', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PSYC15', 'Taylor Smith', 'Psychology');
INSERT INTO Lecturer VALUES ('GEOG16', 'Joshua Miller', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG17', 'Karen Nguyen', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('COMP18', 'Eric Espinoza', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL19', 'Luke Mayer', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MATH20', 'Richard Johnson', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHAR21', 'Joshua Cochran', 'Pharmacy');
INSERT INTO Lecturer VALUES ('NURS22', 'Catherine Abbott', 'Nursing');
INSERT INTO Lecturer VALUES ('SOCI23', 'Ricky Henderson', 'Sociology');
INSERT INTO Lecturer VALUES ('GOVN24', 'Daryl Allison', 'Government');
INSERT INTO Lecturer VALUES ('MED25', 'Michael Mayo', 'Medicine');
INSERT INTO Lecturer VALUES ('MSBM26', 'Lori Gutierrez', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL27', 'Jeffrey Wolf', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PSYC28', 'Emily Sexton', 'Psychology');
INSERT INTO Lecturer VALUES ('MSBM29', 'Tracy Cole', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED30', 'Lisa Russell', 'Medicine');
INSERT INTO Lecturer VALUES ('ECON31', 'David Barr', 'Economics');
INSERT INTO Lecturer VALUES ('CHEM32', 'Matthew King', 'Chemistry');
INSERT INTO Lecturer VALUES ('SOCI33', 'Faith Barrett', 'Sociology');
INSERT INTO Lecturer VALUES ('EPNG34', 'Robert Booth', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CENG35', 'Kimberly Pruitt', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CENG36', 'Matthew King', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL37', 'Anita Williams', 'Life Sciences');
INSERT INTO Lecturer VALUES ('NURS38', 'Alexander White', 'Nursing');
INSERT INTO Lecturer VALUES ('GOVN39', 'Amanda Duran', 'Government');
INSERT INTO Lecturer VALUES ('ECON40', 'Amy Chapman', 'Economics');
INSERT INTO Lecturer VALUES ('COMP41', 'Candace Chavez', 'Computing');
INSERT INTO Lecturer VALUES ('EPNG42', 'James Martinez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS43', 'Daniel Leonard', 'Nursing');
INSERT INTO Lecturer VALUES ('BMNG44', 'Jason Clark', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHYS45', 'Brian Burch', 'Physics');
INSERT INTO Lecturer VALUES ('PHYS46', 'Laura Moreno', 'Physics');
INSERT INTO Lecturer VALUES ('SOCI47', 'Max Butler', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS48', 'Kelly Le', 'Physics');
INSERT INTO Lecturer VALUES ('SOCI49', 'Austin Mullen', 'Sociology');
INSERT INTO Lecturer VALUES ('MSBM50', 'Susan Smith', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PHYS51', 'James Macias', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL52', 'Mary Medina', 'Biology');
INSERT INTO Lecturer VALUES ('CHEM53', 'Rachel Myers', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP54', 'Eric Parker', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL55', 'Corey Howard', 'Biology');
INSERT INTO Lecturer VALUES ('COMP56', 'Stephanie Ramirez', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG57', 'Brian Hale', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL58', 'Chad Mcpherson', 'Biology');
INSERT INTO Lecturer VALUES ('EPNG59', 'Carolyn Padilla', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS60', 'Kirsten Smith', 'Nursing');
INSERT INTO Lecturer VALUES ('EENG61', 'Kathryn Bailey', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM62', 'Ryan Wilson', 'Chemistry');
INSERT INTO Lecturer VALUES ('PSYC63', 'Nathan Butler', 'Psychology');
INSERT INTO Lecturer VALUES ('PHYS64', 'Alison Palmer', 'Physics');
INSERT INTO Lecturer VALUES ('MED65', 'Dr. Ann Hubbard', 'Medicine');
INSERT INTO Lecturer VALUES ('MSBM66', 'Andrew Baker MD', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('SOCI67', 'Kristina Gentry', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL68', 'Adrienne Miller', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MSBM69', 'Mr. Richard Thompson', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('COMP70', 'Ryan Huang', 'Computing');
INSERT INTO Lecturer VALUES ('GOVN71', 'Brian Wong', 'Government');
INSERT INTO Lecturer VALUES ('BIOL72', 'Carla Waller', 'Biology');
INSERT INTO Lecturer VALUES ('COMP73', 'Allison Miller', 'Computing');
INSERT INTO Lecturer VALUES ('ECON74', 'Debra Sanchez', 'Economics');
INSERT INTO Lecturer VALUES ('ECON75', 'Bradley Sanchez', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG76', 'Ashley Huber MD', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CENG77', 'Lori Matthews', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CHEM78', 'Katie Robinson', 'Chemistry');
INSERT INTO Lecturer VALUES ('MED79', 'Javier Hoffman', 'Medicine');
INSERT INTO Lecturer VALUES ('EPNG80', 'John Armstrong', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC81', 'Tina Rivera', 'Psychology');
INSERT INTO Lecturer VALUES ('PSYC82', 'Chad Sanchez', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI83', 'Matthew Bush', 'Sociology');
INSERT INTO Lecturer VALUES ('EENG84', 'Matthew Miller', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL85', 'Gavin Hall', 'Biology');
INSERT INTO Lecturer VALUES ('CENG86', 'Gabriel Wong', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHYS87', 'Robert Hunter', 'Physics');
INSERT INTO Lecturer VALUES ('SOCI88', 'Matthew Khan', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON89', 'Alejandra Jones', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC90', 'Julia Simmons', 'Psychology');
INSERT INTO Lecturer VALUES ('ECON91', 'Christopher Johnson', 'Economics');
INSERT INTO Lecturer VALUES ('MSBM92', 'Daniel Barker', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PSYC93', 'William Perez', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL94', 'Susan Smith', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC95', 'Brandon Gonzalez', 'Psychology');
INSERT INTO Lecturer VALUES ('CENG96', 'Angela Schneider', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS97', 'Colleen Jones', 'Nursing');
INSERT INTO Lecturer VALUES ('PHYS98', 'Robin Flowers', 'Physics');
INSERT INTO Lecturer VALUES ('COMP99', 'David Lin', 'Computing');
INSERT INTO Lecturer VALUES ('GOVN100', 'Wendy Jefferson', 'Government');
INSERT INTO Lecturer VALUES ('SOCI101', 'Richard Rivera', 'Sociology');
INSERT INTO Lecturer VALUES ('PHAR102', 'John Wood', 'Pharmacy');
INSERT INTO Lecturer VALUES ('COMP103', 'Chad Young', 'Computing');
INSERT INTO Lecturer VALUES ('SOCI104', 'Pamela Gilmore', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON105', 'Miranda Howard', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG106', 'Faith Craig', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM107', 'Christopher Garcia', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CENG108', 'Kenneth Ramirez', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CENG109', 'Seth Fleming', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PSYC110', 'Jonathan Carr', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS111', 'Erica Roberts', 'Nursing');
INSERT INTO Lecturer VALUES ('MSBM112', 'Sherry Johnson', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CENG113', 'Michael Mcdonald', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GEOG114', 'Tony Morrow', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG115', 'Christina Brown', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC116', 'Javier Black', 'Psychology');
INSERT INTO Lecturer VALUES ('MED117', 'Ernest Ruiz', 'Medicine');
INSERT INTO Lecturer VALUES ('MATH118', 'Stephanie Frost', 'Mathematics');
INSERT INTO Lecturer VALUES ('MATH119', 'William Martin', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON120', 'Shawn Weber', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG121', 'Robert Powell', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON122', 'Jeremy Bailey', 'Economics');
INSERT INTO Lecturer VALUES ('EENG123', 'Elizabeth Cox', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL124', 'Christopher Hancock', 'Life Sciences');
INSERT INTO Lecturer VALUES ('ECON125', 'Alexander Williams', 'Economics');
INSERT INTO Lecturer VALUES ('CENG126', 'Crystal Black', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('SOCI127', 'James Ray', 'Sociology');
INSERT INTO Lecturer VALUES ('EPNG128', 'Donna Alexander', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GOVN129', 'Valerie Summers', 'Government');
INSERT INTO Lecturer VALUES ('PSYC130', 'Richard Wall', 'Psychology');
INSERT INTO Lecturer VALUES ('MSBM131', 'Jose Rivers', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PHAR132', 'Douglas Johnson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG133', 'Brian Johnson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG134', 'George Pham', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH135', 'Russell Duncan', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHAR136', 'Brian Turner', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG137', 'Michele Anderson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('ECON138', 'Marcus Walker', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC139', 'Brandon Dougherty', 'Psychology');
INSERT INTO Lecturer VALUES ('BMNG140', 'Jane Roman', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('SOCI141', 'Travis Dickerson', 'Sociology');
INSERT INTO Lecturer VALUES ('PSYC142', 'Courtney Jordan', 'Psychology');
INSERT INTO Lecturer VALUES ('ECON143', 'Roberto Rogers', 'Economics');
INSERT INTO Lecturer VALUES ('PHYS144', 'Jacob Dawson', 'Physics');
INSERT INTO Lecturer VALUES ('SOCI145', 'Jeremy Davis', 'Sociology');
INSERT INTO Lecturer VALUES ('CHEM146', 'Jose Robinson', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH147', 'Matthew Burns', 'Mathematics');
INSERT INTO Lecturer VALUES ('SOCI148', 'Andrew Brown', 'Sociology');
INSERT INTO Lecturer VALUES ('PHAR149', 'Jose Mason', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BMNG150', 'Kelly Middleton', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GEOG151', 'Mrs. Sarah Lawrence DDS', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('NURS152', 'Joel Harris', 'Nursing');
INSERT INTO Lecturer VALUES ('CENG153', 'Kristina Johnson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED154', 'Calvin Graham', 'Medicine');
INSERT INTO Lecturer VALUES ('GEOG155', 'Jasmine Stewart DVM', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CENG156', 'Cynthia Anderson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MATH157', 'Zachary Webster', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL158', 'Mary Jones', 'Biology');
INSERT INTO Lecturer VALUES ('PHAR159', 'Alan Fritz', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED160', 'Steven Martin', 'Medicine');
INSERT INTO Lecturer VALUES ('SOCI161', 'Timothy Rogers', 'Sociology');
INSERT INTO Lecturer VALUES ('EPNG162', 'Maureen Owens', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC163', 'Stephanie Ward', 'Psychology');
INSERT INTO Lecturer VALUES ('MED164', 'Hannah Taylor', 'Medicine');
INSERT INTO Lecturer VALUES ('CENG165', 'Kyle Schwartz', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('COMP166', 'Joshua Moore', 'Computing');
INSERT INTO Lecturer VALUES ('SOCI167', 'Jessica Wolfe', 'Sociology');
INSERT INTO Lecturer VALUES ('SOCI168', 'Christy Herman', 'Sociology');
INSERT INTO Lecturer VALUES ('PHAR169', 'Krystal Preston', 'Pharmacy');
INSERT INTO Lecturer VALUES ('COMP170', 'Karl Jackson', 'Computing');
INSERT INTO Lecturer VALUES ('MSBM171', 'Robert Singh', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('EENG172', 'Terry Robinson', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PSYC173', 'Edward Day', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM174', 'Crystal Baker', 'Chemistry');
INSERT INTO Lecturer VALUES ('MED175', 'Dominique Warner', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL176', 'Ann Ross', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PSYC177', 'Daniel Rogers', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM178', 'Tracy Schroeder', 'Chemistry');
INSERT INTO Lecturer VALUES ('CHEM179', 'Stanley Richardson', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHAR180', 'Nicole Martinez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI181', 'Rebecca Malone', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS182', 'Erin Barker', 'Physics');
INSERT INTO Lecturer VALUES ('SOCI183', 'Megan Brooks', 'Sociology');
INSERT INTO Lecturer VALUES ('MATH184', 'Thomas Salinas', 'Mathematics');
INSERT INTO Lecturer VALUES ('EENG185', 'Sarah Gray', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL186', 'Todd Schroeder', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EPNG187', 'Krystal Harper', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM188', 'Daniel Lee', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PSYC189', 'Kenneth Fritz', 'Psychology');
INSERT INTO Lecturer VALUES ('ECON190', 'Rachel Erickson', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG191', 'Vincent Watson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MED192', 'Tiffany Becker', 'Medicine');
INSERT INTO Lecturer VALUES ('MSBM193', 'Lisa Moss', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('SOCI194', 'Yvonne Young', 'Sociology');
INSERT INTO Lecturer VALUES ('MED195', 'Calvin Schwartz', 'Medicine');
INSERT INTO Lecturer VALUES ('MED196', 'Marcus Lopez', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL197', 'Kristin Davenport', 'Biology');
INSERT INTO Lecturer VALUES ('EENG198', 'Raymond Bailey', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('COMP199', 'Jacqueline Bell', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL200', 'Megan Small', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GEOG201', 'Amanda Ingram', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CHEM202', 'Cameron Wilson', 'Chemistry');
INSERT INTO Lecturer VALUES ('GEOG203', 'Jennifer Jenkins', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL204', 'Jackie Romero', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR205', 'Derek Sampson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BMNG206', 'Jason Ruiz', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MATH207', 'Dakota Spencer', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON208', 'Jennifer Medina', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG209', 'Traci Morton', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS210', 'Julie Goodwin', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR211', 'Aimee Roberts', 'Pharmacy');
INSERT INTO Lecturer VALUES ('NURS212', 'Michael Hughes', 'Nursing');
INSERT INTO Lecturer VALUES ('SOCI213', 'Denise White', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS214', 'Jerry Jackson', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM215', 'Gary Stevens', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL216', 'Rachel Drake', 'Biology');
INSERT INTO Lecturer VALUES ('ECON217', 'Samuel Kelly', 'Economics');
INSERT INTO Lecturer VALUES ('MATH218', 'Rhonda Gonzalez', 'Mathematics');
INSERT INTO Lecturer VALUES ('MED219', 'William Coffey', 'Medicine');
INSERT INTO Lecturer VALUES ('SOCI220', 'Rebecca Martin', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON221', 'Kathy Hunter', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL222', 'Jodi Nelson', 'Biology');
INSERT INTO Lecturer VALUES ('CHEM223', 'Alex Vasquez', 'Chemistry');
INSERT INTO Lecturer VALUES ('GOVN224', 'Jennifer Shaw', 'Government');
INSERT INTO Lecturer VALUES ('CHEM225', 'Daniel Mcgee', 'Chemistry');
INSERT INTO Lecturer VALUES ('ECON226', 'Gerald Ortiz', 'Economics');
INSERT INTO Lecturer VALUES ('MSBM227', 'Emily Smith', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED228', 'James King', 'Medicine');
INSERT INTO Lecturer VALUES ('MATH229', 'Adam Newman', 'Mathematics');
INSERT INTO Lecturer VALUES ('CHEM230', 'Brandy Stark', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP231', 'Beth Nguyen', 'Computing');
INSERT INTO Lecturer VALUES ('CHEM232', 'Randy Brown', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL233', 'Thomas Martin', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR234', 'Connie Jones', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MSBM235', 'Ryan Rubio', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('EPNG236', 'Theresa Davis', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('ECON237', 'Joshua Price', 'Economics');
INSERT INTO Lecturer VALUES ('GOVN238', 'Tim Gomez', 'Government');
INSERT INTO Lecturer VALUES ('BMNG239', 'Timothy Mckenzie', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MED240', 'Sonya Garner', 'Medicine');
INSERT INTO Lecturer VALUES ('NURS241', 'Teresa Watts', 'Nursing');
INSERT INTO Lecturer VALUES ('CENG242', 'Christopher Spencer', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('EPNG243', 'Mark Jones', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('ECON244', 'Alexandra Holmes', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL245', 'Jessica Mcfarland', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR246', 'Cynthia Morrison', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL247', 'Andrew Anderson', 'Biology');
INSERT INTO Lecturer VALUES ('BMNG248', 'Mrs. Kathy Martinez', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PSYC249', 'Maria Torres', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI250', 'Keith Skinner Jr.', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS251', 'Lance Campbell', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH252', 'Thomas Mcpherson', 'Mathematics');
INSERT INTO Lecturer VALUES ('COMP253', 'Thomas Torres', 'Computing');
INSERT INTO Lecturer VALUES ('NURS254', 'Sara Curtis', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL255', 'Cristina Castro', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BMNG256', 'Carrie Olsen', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON257', 'Sherry Perry', 'Economics');
INSERT INTO Lecturer VALUES ('GEOG258', 'Sean Hawkins', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHAR259', 'Robert Pacheco', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PSYC260', 'Brandon Patterson', 'Psychology');
INSERT INTO Lecturer VALUES ('PSYC261', 'Shawn Parks', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG262', 'Kirk Vazquez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BMNG263', 'Antonio Bradshaw', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHAR264', 'Amy Carpenter', 'Pharmacy');
INSERT INTO Lecturer VALUES ('ECON265', 'Sonia Gonzalez', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC266', 'Michael Green', 'Psychology');
INSERT INTO Lecturer VALUES ('ECON267', 'Cynthia Bryant MD', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL268', 'John Hall', 'Biology');
INSERT INTO Lecturer VALUES ('GOVN269', 'Victoria Mcdowell', 'Government');
INSERT INTO Lecturer VALUES ('PHAR270', 'Tyler Burgess', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHAR271', 'Gary Young', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL272', 'Charles Roberts', 'Biology');
INSERT INTO Lecturer VALUES ('SOCI273', 'Joseph Cox', 'Sociology');
INSERT INTO Lecturer VALUES ('PSYC274', 'Theresa Ochoa', 'Psychology');
INSERT INTO Lecturer VALUES ('PHAR275', 'Brooke Flores', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL276', 'Desiree Waters', 'Life Sciences');
INSERT INTO Lecturer VALUES ('COMP277', 'Duane White', 'Computing');
INSERT INTO Lecturer VALUES ('ECON278', 'Nancy Conley', 'Economics');
INSERT INTO Lecturer VALUES ('GEOG279', 'Allison Grimes', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHAR280', 'Karen Hancock', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHAR281', 'Kimberly Turner', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CENG282', 'Vanessa Galloway', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('ECON283', 'James Ochoa', 'Economics');
INSERT INTO Lecturer VALUES ('MATH284', 'Monica Wallace', 'Mathematics');
INSERT INTO Lecturer VALUES ('SOCI285', 'Lydia Cummings', 'Sociology');
INSERT INTO Lecturer VALUES ('PHAR286', 'Emily Chavez MD', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL287', 'Matthew Walton', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EENG288', 'Connor Brock', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR289', 'Carrie Pace', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL290', 'Ryan Chavez', 'Biology');
INSERT INTO Lecturer VALUES ('MED291', 'Amanda Rodriguez', 'Medicine');
INSERT INTO Lecturer VALUES ('SOCI292', 'Jason Pennington', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS293', 'Juan Brooks', 'Physics');
INSERT INTO Lecturer VALUES ('PSYC294', 'Barbara Gallegos', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM295', 'Ronald Collier', 'Chemistry');
INSERT INTO Lecturer VALUES ('SOCI296', 'Brittney Smith', 'Sociology');
INSERT INTO Lecturer VALUES ('EENG297', 'Eric Moss', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MSBM298', 'Richard Becker', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MATH299', 'Matthew Abbott', 'Mathematics');
INSERT INTO Lecturer VALUES ('NURS300', 'Carla Lewis', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR301', 'Courtney Vega', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL302', 'Jamie Walker', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MED303', 'Brooke Guerrero', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL304', 'Frank Miller', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EENG305', 'Francis King', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GEOG306', 'Amanda Serrano', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EENG307', 'Anthony Durham', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GOVN308', 'Scott Garcia', 'Government');
INSERT INTO Lecturer VALUES ('ECON309', 'Debbie Rivera', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG310', 'Shirley Lee', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PSYC311', 'Jay Mann', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM312', 'David Walsh', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP313', 'Cheryl Benson', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR314', 'Aaron Howard', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BMNG315', 'John Mayer', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EPNG316', 'Anthony Dickerson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('ECON317', 'Brandon Robinson', 'Economics');
INSERT INTO Lecturer VALUES ('NURS318', 'Tyler Edwards', 'Nursing');
INSERT INTO Lecturer VALUES ('GEOG319', 'Kurt Holloway', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG320', 'Charles Smith', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('COMP321', 'Erin Miller', 'Computing');
INSERT INTO Lecturer VALUES ('MED322', 'Randall Simpson', 'Medicine');
INSERT INTO Lecturer VALUES ('GEOG323', 'Erin Miller', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG324', 'Andrew Rojas', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHAR325', 'Diane Meyer', 'Pharmacy');
INSERT INTO Lecturer VALUES ('NURS326', 'Heather Miller', 'Nursing');
INSERT INTO Lecturer VALUES ('ECON327', 'Laurie Sanchez', 'Economics');
INSERT INTO Lecturer VALUES ('PHYS328', 'Kiara Dunn', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL329', 'Justin Delgado', 'Biology');
INSERT INTO Lecturer VALUES ('ECON330', 'Michelle Myers', 'Economics');
INSERT INTO Lecturer VALUES ('CENG331', 'Matthew Wilkinson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GOVN332', 'Cheryl Rangel', 'Government');
INSERT INTO Lecturer VALUES ('GEOG333', 'Jessica Nelson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('ECON334', 'Crystal Phillips', 'Economics');
INSERT INTO Lecturer VALUES ('SOCI335', 'Dr. Kevin Hurley Jr.', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL336', 'Adam Barron', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL337', 'Lauren Pena', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL338', 'Mr. Brian Davis', 'Biology');
INSERT INTO Lecturer VALUES ('EENG339', 'Michael Atkins', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('NURS340', 'Nancy Gonzalez', 'Nursing');
INSERT INTO Lecturer VALUES ('COMP341', 'Rebecca Lewis', 'Computing');
INSERT INTO Lecturer VALUES ('EENG342', 'Heather Mccormick', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GEOG343', 'Carmen Davis', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG344', 'Jacob Villegas', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GEOG345', 'Stacy Taylor', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BMNG346', 'Kyle Romero', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL347', 'Thomas Gomez', 'Life Sciences');
INSERT INTO Lecturer VALUES ('SOCI348', 'Nicole Brown', 'Sociology');
INSERT INTO Lecturer VALUES ('EENG349', 'Billy Blevins', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL350', 'Alexis Barber', 'Biology');
INSERT INTO Lecturer VALUES ('MATH351', 'Joshua Montgomery', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON352', 'Jeremy Moore', 'Economics');
INSERT INTO Lecturer VALUES ('SOCI353', 'Julie Graham', 'Sociology');
INSERT INTO Lecturer VALUES ('MATH354', 'Anthony Gray', 'Mathematics');
INSERT INTO Lecturer VALUES ('EENG355', 'Joshua Barnes', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('SOCI356', 'Lauren Drake', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL357', 'Shirley Estes', 'Biology');
INSERT INTO Lecturer VALUES ('COMP358', 'Ashley Vazquez', 'Computing');
INSERT INTO Lecturer VALUES ('COMP359', 'Dana Bright', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL360', 'Edward Wilson', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR361', 'Ryan Key', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG362', 'Leah Baker', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BMNG363', 'Amy Martinez', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('NURS364', 'Mr. Scott Marquez', 'Nursing');
INSERT INTO Lecturer VALUES ('EENG365', 'Mariah Ramsey', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PSYC366', 'Monica Simon', 'Psychology');
INSERT INTO Lecturer VALUES ('MATH367', 'Molly Hammond', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHYS368', 'Samantha Price', 'Physics');
INSERT INTO Lecturer VALUES ('CHEM369', 'Ralph Espinoza', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL370', 'Javier Howard', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GEOG371', 'Jennifer Walters', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EENG372', 'Alex Shelton', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('NURS373', 'Richard Stevens', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC374', 'Robert Boyle', 'Psychology');
INSERT INTO Lecturer VALUES ('GEOG375', 'Barry Manning', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL376', 'Angela Walsh', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC377', 'Nicholas Snyder', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI378', 'John Conley', 'Sociology');
INSERT INTO Lecturer VALUES ('MATH379', 'Robin Ward', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG380', 'Jeremy Davis', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHAR381', 'Amanda Braun', 'Pharmacy');
INSERT INTO Lecturer VALUES ('ECON382', 'Matthew Hanson', 'Economics');
INSERT INTO Lecturer VALUES ('MATH383', 'Lisa Pierce', 'Mathematics');
INSERT INTO Lecturer VALUES ('BMNG384', 'Katrina Tucker', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG385', 'Vanessa Miller', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GOVN386', 'Lori Franklin', 'Government');
INSERT INTO Lecturer VALUES ('CHEM387', 'Donald Rosales', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH388', 'Francisco Smith', 'Mathematics');
INSERT INTO Lecturer VALUES ('GOVN389', 'Dr. Harold Reyes', 'Government');
INSERT INTO Lecturer VALUES ('GEOG390', 'Robin Vargas', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH391', 'Chad Jackson', 'Mathematics');
INSERT INTO Lecturer VALUES ('PSYC392', 'Walter Bishop', 'Psychology');
INSERT INTO Lecturer VALUES ('COMP393', 'Karen Campbell', 'Computing');
INSERT INTO Lecturer VALUES ('MATH394', 'Ronald Myers', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG395', 'Robert Mendez', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MSBM396', 'Troy Adkins', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL397', 'Robert Skinner', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BMNG398', 'Donna Ruiz', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('NURS399', 'David Hill', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL400', 'Savannah Wilson', 'Life Sciences');
INSERT INTO Lecturer VALUES ('ECON401', 'Krista Bradford', 'Economics');
INSERT INTO Lecturer VALUES ('SOCI402', 'Louis Mata', 'Sociology');
INSERT INTO Lecturer VALUES ('GEOG403', 'Yvette Arroyo', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('SOCI404', 'Paul Stanley', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON405', 'Sarah Charles', 'Economics');
INSERT INTO Lecturer VALUES ('GOVN406', 'Jesse Miller', 'Government');
INSERT INTO Lecturer VALUES ('BIOL407', 'John Owen DDS', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MSBM408', 'Chad Smith', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('SOCI409', 'Kathy Mejia', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS410', 'Anna Saunders MD', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC411', 'Jesse Potts', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI412', 'Joshua Lawrence', 'Sociology');
INSERT INTO Lecturer VALUES ('SOCI413', 'Mrs. Kimberly Hoffman', 'Sociology');
INSERT INTO Lecturer VALUES ('SOCI414', 'Shelby Martinez', 'Sociology');
INSERT INTO Lecturer VALUES ('MATH415', 'Johnny Kramer', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG416', 'Dorothy Greene', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PSYC417', 'Christine White', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM418', 'Katrina Lee', 'Chemistry');
INSERT INTO Lecturer VALUES ('EPNG419', 'Andrew Peters', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('SOCI420', 'Mark Marsh', 'Sociology');
INSERT INTO Lecturer VALUES ('PSYC421', 'Ashley George', 'Psychology');
INSERT INTO Lecturer VALUES ('MSBM422', 'Marie Andrews', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL423', 'James Walker', 'Biology');
INSERT INTO Lecturer VALUES ('MATH424', 'Jessica Gill', 'Mathematics');
INSERT INTO Lecturer VALUES ('MATH425', 'Rebecca Phillips', 'Mathematics');
INSERT INTO Lecturer VALUES ('GOVN426', 'Nathan York', 'Government');
INSERT INTO Lecturer VALUES ('MSBM427', 'Stephen Garrett', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('GOVN428', 'Zachary Jones', 'Government');
INSERT INTO Lecturer VALUES ('MATH429', 'Cindy Bryant', 'Mathematics');
INSERT INTO Lecturer VALUES ('NURS430', 'Susan Avila', 'Nursing');
INSERT INTO Lecturer VALUES ('GOVN431', 'Yvonne Miller', 'Government');
INSERT INTO Lecturer VALUES ('ECON432', 'Thomas Roberts', 'Economics');
INSERT INTO Lecturer VALUES ('SOCI433', 'Mark Griffin', 'Sociology');
INSERT INTO Lecturer VALUES ('PHAR434', 'Nicole Garcia', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED435', 'Nicholas Williams', 'Medicine');
INSERT INTO Lecturer VALUES ('GEOG436', 'Emily Gonzalez', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG437', 'Daniel Wright', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GEOG438', 'Scott Smith', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CENG439', 'Nicholas Costa', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('COMP440', 'John Cooper', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR441', 'Sara Mcintosh', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CENG442', 'Julia Roberts', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CHEM443', 'Brandi Sparks', 'Chemistry');
INSERT INTO Lecturer VALUES ('CHEM444', 'Andrew Morton', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH445', 'Cynthia Ellis DDS', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL446', 'Justin Watts', 'Biology');
INSERT INTO Lecturer VALUES ('BMNG447', 'Kelly Bates', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GOVN448', 'Bryan Smith', 'Government');
INSERT INTO Lecturer VALUES ('MATH449', 'Oscar Miller', 'Mathematics');
INSERT INTO Lecturer VALUES ('GOVN450', 'Jennifer Hall', 'Government');
INSERT INTO Lecturer VALUES ('EPNG451', 'Anthony Duke', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG452', 'Pamela Carter', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('ECON453', 'Melissa Medina', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC454', 'Albert Green', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI455', 'Amanda Stephenson', 'Sociology');
INSERT INTO Lecturer VALUES ('MSBM456', 'Richard Elliott', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CENG457', 'Lisa Martinez', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MATH458', 'Mrs. Brenda Owens', 'Mathematics');
INSERT INTO Lecturer VALUES ('MED459', 'Kathy Dixon', 'Medicine');
INSERT INTO Lecturer VALUES ('NURS460', 'Ashley Anderson', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL461', 'Jessica Underwood', 'Life Sciences');
INSERT INTO Lecturer VALUES ('NURS462', 'Kimberly Harrison', 'Nursing');
INSERT INTO Lecturer VALUES ('EPNG463', 'Robert White', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MATH464', 'Alexis Jordan', 'Mathematics');
INSERT INTO Lecturer VALUES ('MATH465', 'James Cox', 'Mathematics');
INSERT INTO Lecturer VALUES ('PSYC466', 'Robert Butler', 'Psychology');
INSERT INTO Lecturer VALUES ('BMNG467', 'Robert Ramirez', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EENG468', 'Rhonda Rogers', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EPNG469', 'Harry Mcgrath', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('COMP470', 'Erica White', 'Computing');
INSERT INTO Lecturer VALUES ('SOCI471', 'Jimmy Moore', 'Sociology');
INSERT INTO Lecturer VALUES ('CHEM472', 'Melanie Grimes', 'Chemistry');
INSERT INTO Lecturer VALUES ('EENG473', 'Sara Cox', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GEOG474', 'Felicia Riddle', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CHEM475', 'Lindsay Frazier', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHYS476', 'Dave Gibson', 'Physics');
INSERT INTO Lecturer VALUES ('GEOG477', 'Shelby Pena', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('ECON478', 'John Jacobs', 'Economics');
INSERT INTO Lecturer VALUES ('ECON479', 'Joshua Price', 'Economics');
INSERT INTO Lecturer VALUES ('EENG480', 'Michael Butler', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MSBM481', 'Jennifer Scott', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CHEM482', 'Joseph Sosa', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP483', 'Rachel Hill', 'Computing');
INSERT INTO Lecturer VALUES ('EENG484', 'Andrew Houston', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('NURS485', 'Christopher White', 'Nursing');
INSERT INTO Lecturer VALUES ('SOCI486', 'Gail Reese', 'Sociology');
INSERT INTO Lecturer VALUES ('MED487', 'Christian Morrison', 'Medicine');
INSERT INTO Lecturer VALUES ('MED488', 'Paul Noble', 'Medicine');
INSERT INTO Lecturer VALUES ('EPNG489', 'George Gomez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC490', 'Valerie Scott', 'Psychology');
INSERT INTO Lecturer VALUES ('PHAR491', 'Andrew Price', 'Pharmacy');
INSERT INTO Lecturer VALUES ('ECON492', 'Juan Johnson', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG493', 'Jason Bradford', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MATH494', 'Melissa May', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHAR495', 'Mary Ortiz', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BMNG496', 'Meredith Liu', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('NURS497', 'Marc Henderson', 'Nursing');
INSERT INTO Lecturer VALUES ('MED498', 'Antonio Thompson', 'Medicine');
INSERT INTO Lecturer VALUES ('GOVN499', 'Christopher Haley', 'Government');
INSERT INTO Lecturer VALUES ('PHAR500', 'Jennifer Clark', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EPNG501', 'Jimmy Young', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('COMP502', 'Adam Collins', 'Computing');
INSERT INTO Lecturer VALUES ('MED503', 'Kimberly Kane', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL504', 'Richard Richardson', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CENG505', 'Susan Smith', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MSBM506', 'Jennifer Smith', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('COMP507', 'Julia Hoover', 'Computing');
INSERT INTO Lecturer VALUES ('COMP508', 'Tina Jarvis', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL509', 'Bradley Higgins', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BMNG510', 'Lori Cole', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP511', 'Brian Hall', 'Computing');
INSERT INTO Lecturer VALUES ('PHYS512', 'Nicholas Flores', 'Physics');
INSERT INTO Lecturer VALUES ('ECON513', 'Jennifer Robinson', 'Economics');
INSERT INTO Lecturer VALUES ('GEOG514', 'Daniel Pennington', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH515', 'Lindsey Gonzalez', 'Mathematics');
INSERT INTO Lecturer VALUES ('MED516', 'Daniel Green', 'Medicine');
INSERT INTO Lecturer VALUES ('BMNG517', 'Richard Hanna', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CENG518', 'Amy Henderson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('EENG519', 'Amy Alexander', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EENG520', 'Herbert Burns', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHYS521', 'Joy Frost', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM522', 'Alyssa Reynolds', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON523', 'Anthony Jackson', 'Economics');
INSERT INTO Lecturer VALUES ('MSBM524', 'Michael Robertson', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CENG525', 'Brittany Owens', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MATH526', 'Daniel Fox', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG527', 'Christine Perry', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH528', 'Mariah Sandoval', 'Mathematics');
INSERT INTO Lecturer VALUES ('MATH529', 'Mark Randall', 'Mathematics');
INSERT INTO Lecturer VALUES ('CHEM530', 'Jason Robinson', 'Chemistry');
INSERT INTO Lecturer VALUES ('GEOG531', 'Deborah Farrell', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MSBM532', 'Jimmy Richardson', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PSYC533', 'Steven Estrada', 'Psychology');
INSERT INTO Lecturer VALUES ('PHAR534', 'Amanda Davis MD', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED535', 'Heather White', 'Medicine');
INSERT INTO Lecturer VALUES ('MED536', 'Emily Lewis', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC537', 'James Scott', 'Psychology');
INSERT INTO Lecturer VALUES ('MATH538', 'Duane Houston', 'Mathematics');
INSERT INTO Lecturer VALUES ('EPNG539', 'Mr. Ryan Garcia', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('COMP540', 'Kelly Green', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL541', 'Anita Roberts', 'Biology');
INSERT INTO Lecturer VALUES ('PHYS542', 'Valerie Cox', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL543', 'Bill Bush', 'Biology');
INSERT INTO Lecturer VALUES ('CHEM544', 'Michael James', 'Chemistry');
INSERT INTO Lecturer VALUES ('EENG545', 'Thomas Hardy', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('ECON546', 'Melissa Johnson', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL547', 'Natalie Chase', 'Life Sciences');
INSERT INTO Lecturer VALUES ('SOCI548', 'Amy Clark', 'Sociology');
INSERT INTO Lecturer VALUES ('GEOG549', 'Laura Johnson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL550', 'Jason Nelson', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC551', 'Nicole Frost', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG552', 'Dean Galvan', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EENG553', 'Brittany Dunn', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MSBM554', 'Andrew Wright', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BMNG555', 'James Gomez', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EENG556', 'Felicia Miller', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MSBM557', 'Sarah Hughes', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PSYC558', 'David Crawford', 'Psychology');
INSERT INTO Lecturer VALUES ('CENG559', 'Shannon Anderson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED560', 'Breanna Foley', 'Medicine');
INSERT INTO Lecturer VALUES ('SOCI561', 'Nicole Evans', 'Sociology');
INSERT INTO Lecturer VALUES ('CENG562', 'Kevin Preston', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CENG563', 'Heather Long', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL564', 'Amanda Pham', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL565', 'James Collins', 'Biology');
INSERT INTO Lecturer VALUES ('GEOG566', 'Randy Ward', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EENG567', 'Tyler Maddox', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('ECON568', 'Jenny Taylor', 'Economics');
INSERT INTO Lecturer VALUES ('GOVN569', 'Angela Adams', 'Government');
INSERT INTO Lecturer VALUES ('BIOL570', 'Jessica Santiago', 'Life Sciences');
INSERT INTO Lecturer VALUES ('SOCI571', 'Mr. Richard Johnson', 'Sociology');
INSERT INTO Lecturer VALUES ('BMNG572', 'Julie Harrison', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MSBM573', 'Ronald Alvarez', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('COMP574', 'Heather Salazar', 'Computing');
INSERT INTO Lecturer VALUES ('GOVN575', 'Amber Perry', 'Government');
INSERT INTO Lecturer VALUES ('PSYC576', 'Lisa Grant', 'Psychology');
INSERT INTO Lecturer VALUES ('GEOG577', 'Ricardo James', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG578', 'Molly Greene', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GOVN579', 'Jason Ortiz', 'Government');
INSERT INTO Lecturer VALUES ('MED580', 'Gregory Figueroa', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC581', 'David Davis', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL582', 'Jeffrey Hines', 'Biology');
INSERT INTO Lecturer VALUES ('SOCI583', 'Ricardo Le', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS584', 'John Flowers', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR585', 'Whitney Steele', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL586', 'Teresa Bailey', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR587', 'Brittany Stout', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EENG588', 'Mercedes Pearson', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM589', 'Richard Martin', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHAR590', 'Gregory Pollard', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHYS591', 'Elizabeth Martin', 'Physics');
INSERT INTO Lecturer VALUES ('GOVN592', 'Mr. Eric Reeves', 'Government');
INSERT INTO Lecturer VALUES ('BIOL593', 'Amanda Ramirez', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MATH594', 'Michael Bass', 'Mathematics');
INSERT INTO Lecturer VALUES ('NURS595', 'Jeanette Vargas', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR596', 'Danny Thompson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BMNG597', 'Kathryn Baker', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP598', 'Scott Thomas', 'Computing');
INSERT INTO Lecturer VALUES ('NURS599', 'Jennifer Skinner', 'Nursing');
INSERT INTO Lecturer VALUES ('COMP600', 'Noah West', 'Computing');
INSERT INTO Lecturer VALUES ('MED601', 'Ryan Richards', 'Medicine');
INSERT INTO Lecturer VALUES ('CHEM602', 'Regina Lin', 'Chemistry');
INSERT INTO Lecturer VALUES ('EENG603', 'Anna Hines', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('COMP604', 'Brandon Jackson', 'Computing');
INSERT INTO Lecturer VALUES ('CHEM605', 'Taylor Barajas', 'Chemistry');
INSERT INTO Lecturer VALUES ('SOCI606', 'Shannon Perkins', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS607', 'Colleen Lopez', 'Physics');
INSERT INTO Lecturer VALUES ('GEOG608', 'Katrina Mack', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EENG609', 'Sarah Page', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MED610', 'Joseph Jones', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL611', 'Sarah Washington', 'Life Sciences');
INSERT INTO Lecturer VALUES ('NURS612', 'Gabrielle Gillespie', 'Nursing');
INSERT INTO Lecturer VALUES ('PHYS613', 'Charles Villanueva', 'Physics');
INSERT INTO Lecturer VALUES ('EPNG614', 'Kevin Adams', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS615', 'Brandon Cabrera', 'Nursing');
INSERT INTO Lecturer VALUES ('CHEM616', 'Whitney Jones', 'Chemistry');
INSERT INTO Lecturer VALUES ('ECON617', 'Lance Clark', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC618', 'Laura Rose', 'Psychology');
INSERT INTO Lecturer VALUES ('MED619', 'Julia Williamson', 'Medicine');
INSERT INTO Lecturer VALUES ('COMP620', 'Anthony Henry', 'Computing');
INSERT INTO Lecturer VALUES ('CHEM621', 'Judy Lee', 'Chemistry');
INSERT INTO Lecturer VALUES ('MSBM622', 'Lauren Hill', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL623', 'Robert Sims', 'Biology');
INSERT INTO Lecturer VALUES ('MED624', 'Tara Knight', 'Medicine');
INSERT INTO Lecturer VALUES ('GOVN625', 'Randall Alexander', 'Government');
INSERT INTO Lecturer VALUES ('BIOL626', 'Anthony Rose', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CENG627', 'Jon Herrera', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('EPNG628', 'Caleb Greene', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EENG629', 'Ana Bauer', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('NURS630', 'Luke Espinoza', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH631', 'Madison Dudley', 'Mathematics');
INSERT INTO Lecturer VALUES ('EPNG632', 'Eric Jarvis', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GOVN633', 'Chelsea Clark', 'Government');
INSERT INTO Lecturer VALUES ('PHYS634', 'Thomas Joseph', 'Physics');
INSERT INTO Lecturer VALUES ('GOVN635', 'Margaret Collier', 'Government');
INSERT INTO Lecturer VALUES ('BIOL636', 'Douglas Mitchell', 'Biology');
INSERT INTO Lecturer VALUES ('MED637', 'Jennifer Chavez', 'Medicine');
INSERT INTO Lecturer VALUES ('COMP638', 'Scott Sanders', 'Computing');
INSERT INTO Lecturer VALUES ('CHEM639', 'Timothy Lawrence', 'Chemistry');
INSERT INTO Lecturer VALUES ('EPNG640', 'Sara Rodriguez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('COMP641', 'Mary Roberts', 'Computing');
INSERT INTO Lecturer VALUES ('SOCI642', 'Mrs. Shannon Frazier PhD', 'Sociology');
INSERT INTO Lecturer VALUES ('MED643', 'Sherry Fischer', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL644', 'John Todd', 'Biology');
INSERT INTO Lecturer VALUES ('EENG645', 'Nathan Campbell', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM646', 'Lisa Hurst', 'Chemistry');
INSERT INTO Lecturer VALUES ('SOCI647', 'Jacob Blevins DVM', 'Sociology');
INSERT INTO Lecturer VALUES ('CHEM648', 'Anna Stevens', 'Chemistry');
INSERT INTO Lecturer VALUES ('CHEM649', 'Karen Kelley', 'Chemistry');
INSERT INTO Lecturer VALUES ('EPNG650', 'Pedro Bauer', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG651', 'Steven Jennings', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC652', 'Crystal Carpenter', 'Psychology');
INSERT INTO Lecturer VALUES ('PHAR653', 'Nicholas Gordon', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EENG654', 'Cristina Haney', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MSBM655', 'Becky Evans', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PHYS656', 'Jack White', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM657', 'Paul Smith', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PHYS658', 'Mrs. Marissa Dennis', 'Physics');
INSERT INTO Lecturer VALUES ('CHEM659', 'Joshua Sanders', 'Chemistry');
INSERT INTO Lecturer VALUES ('CHEM660', 'Jenna Wright', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH661', 'Natasha Hughes', 'Mathematics');
INSERT INTO Lecturer VALUES ('NURS662', 'William Blake', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL663', 'Kimberly Gonzalez', 'Life Sciences');
INSERT INTO Lecturer VALUES ('COMP664', 'Ian Cole', 'Computing');
INSERT INTO Lecturer VALUES ('CENG665', 'Joshua Carpenter', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHAR666', 'Courtney Novak', 'Pharmacy');
INSERT INTO Lecturer VALUES ('COMP667', 'Kevin Perry', 'Computing');
INSERT INTO Lecturer VALUES ('ECON668', 'Donald Blair', 'Economics');
INSERT INTO Lecturer VALUES ('CHEM669', 'Allison Lewis', 'Chemistry');
INSERT INTO Lecturer VALUES ('PSYC670', 'Shannon Mendez', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL671', 'Jason Nguyen', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EPNG672', 'Rachel Henry', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BMNG673', 'Brianna Sandoval', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('SOCI674', 'Johnathan Webster', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS675', 'Jessica Thomas', 'Nursing');
INSERT INTO Lecturer VALUES ('BMNG676', 'Paula King', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHAR677', 'Richard Jackson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CHEM678', 'Richard Faulkner', 'Chemistry');
INSERT INTO Lecturer VALUES ('PSYC679', 'Shawna Johnson', 'Psychology');
INSERT INTO Lecturer VALUES ('MATH680', 'Megan Cantu', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHAR681', 'Kim Garrett', 'Pharmacy');
INSERT INTO Lecturer VALUES ('COMP682', 'Jeffrey Paul', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR683', 'Brooke Martin', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED684', 'Terri Morris', 'Medicine');
INSERT INTO Lecturer VALUES ('BMNG685', 'Mr. William Powell', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CENG686', 'Sarah Jones', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('ECON687', 'James Thompson', 'Economics');
INSERT INTO Lecturer VALUES ('MED688', 'Jordan Rodgers', 'Medicine');
INSERT INTO Lecturer VALUES ('COMP689', 'Christopher Romero', 'Computing');
INSERT INTO Lecturer VALUES ('MSBM690', 'Mr. Stephen Lopez DDS', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('GEOG691', 'Alexis Sanders', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL692', 'Michael Hunt', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MSBM693', 'John Daniel', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON694', 'Brandon Thomas', 'Economics');
INSERT INTO Lecturer VALUES ('MED695', 'Maria Harris', 'Medicine');
INSERT INTO Lecturer VALUES ('EENG696', 'Christopher Martinez', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR697', 'Amanda Kramer', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EENG698', 'Amy Gray', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EPNG699', 'Caleb Rivers', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CENG700', 'Timothy Hartman', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BMNG701', 'Benjamin Dennis', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MSBM702', 'Lisa Leach', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CENG703', 'Pamela Williams', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MATH704', 'Pamela Lopez', 'Mathematics');
INSERT INTO Lecturer VALUES ('BMNG705', 'Brandy Parker', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHYS706', 'Bradley Stanton', 'Physics');
INSERT INTO Lecturer VALUES ('GEOG707', 'Kiara Ward', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GOVN708', 'John Colon', 'Government');
INSERT INTO Lecturer VALUES ('BMNG709', 'Robert Higgins', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('NURS710', 'Michael Collins', 'Nursing');
INSERT INTO Lecturer VALUES ('GOVN711', 'Kimberly Foster', 'Government');
INSERT INTO Lecturer VALUES ('GOVN712', 'Barry Simpson', 'Government');
INSERT INTO Lecturer VALUES ('BIOL713', 'Jessica Wood', 'Biology');
INSERT INTO Lecturer VALUES ('SOCI714', 'Sue Anderson', 'Sociology');
INSERT INTO Lecturer VALUES ('SOCI715', 'Laura Harris', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL716', 'Carla Smith', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC717', 'Melinda Diaz MD', 'Psychology');
INSERT INTO Lecturer VALUES ('ECON718', 'Corey Leonard', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL719', 'Adrian Mckinney', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BMNG720', 'Becky Williams', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('NURS721', 'Joshua Mcgee', 'Nursing');
INSERT INTO Lecturer VALUES ('MED722', 'Amy Garcia', 'Medicine');
INSERT INTO Lecturer VALUES ('EPNG723', 'Scott Johnson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BIOL724', 'Michael Martin', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PSYC725', 'Tammie Cook', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI726', 'Bryan Stein', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL727', 'Angel Flynn', 'Biology');
INSERT INTO Lecturer VALUES ('CHEM728', 'Maria Parrish', 'Chemistry');
INSERT INTO Lecturer VALUES ('NURS729', 'Brandy Middleton', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH730', 'Nicholas Newman', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG731', 'Isaiah Ford', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG732', 'Adam Fisher', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM733', 'Anthony Perez', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL734', 'Jamie Turner', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL735', 'Michael Powell', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BMNG736', 'Alyssa Benton MD', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MED737', 'John Jones', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC738', 'Alicia Green', 'Psychology');
INSERT INTO Lecturer VALUES ('MATH739', 'Sarah Shaw', 'Mathematics');
INSERT INTO Lecturer VALUES ('MSBM740', 'Michelle Reynolds', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('GOVN741', 'Justin Jacobs', 'Government');
INSERT INTO Lecturer VALUES ('ECON742', 'Angela Hatfield', 'Economics');
INSERT INTO Lecturer VALUES ('COMP743', 'Madison Bell', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR744', 'Herbert Johnson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL745', 'Sara Jones', 'Biology');
INSERT INTO Lecturer VALUES ('MED746', 'Ronald Kelley', 'Medicine');
INSERT INTO Lecturer VALUES ('ECON747', 'Stephen Johnson', 'Economics');
INSERT INTO Lecturer VALUES ('MED748', 'Ricky Clark', 'Medicine');
INSERT INTO Lecturer VALUES ('NURS749', 'Maria Morton', 'Nursing');
INSERT INTO Lecturer VALUES ('CHEM750', 'David Zimmerman', 'Chemistry');

