USE OURVLECloneDatabase;

 ──── Lecturers ────────────────────────────────────────────────────────────────────
INSERT INTO Lecturer VALUES ('BMNG1', 'John Floyd', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP2', 'David Robinson', 'Computing');
INSERT INTO Lecturer VALUES ('COMP3', 'James Mclean', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL4', 'Julie Tucker', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BMNG5', 'Amanda Macdonald', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('NURS6', 'Michael Harris', 'Nursing');
INSERT INTO Lecturer VALUES ('MED7', 'Dawn Crawford', 'Medicine');
INSERT INTO Lecturer VALUES ('MED8', 'Robert Baker', 'Medicine');
INSERT INTO Lecturer VALUES ('MATH9', 'Edward Thomas MD', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL10', 'Eric Ibarra', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GEOG11', 'Stephanie White', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('NURS12', 'Dana Ferguson', 'Nursing');
INSERT INTO Lecturer VALUES ('PHYS13', 'Kevin Knight', 'Physics');
INSERT INTO Lecturer VALUES ('COMP14', 'Jessica Jones PhD', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR15', 'Cole Mosley', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL16', 'Melanie Myers', 'Biology');
INSERT INTO Lecturer VALUES ('CHEM17', 'Sara Jenkins', 'Chemistry');
INSERT INTO Lecturer VALUES ('GEOG18', 'Terrance Davidson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHYS19', 'Carla Brown', 'Physics');
INSERT INTO Lecturer VALUES ('PSYC20', 'Richard Bush', 'Psychology');
INSERT INTO Lecturer VALUES ('MSBM21', 'Renee Hodges', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL22', 'Allen Johnson', 'Biology');
INSERT INTO Lecturer VALUES ('EENG23', 'Joanne Krause', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PSYC24', 'Patricia Brown', 'Psychology');
INSERT INTO Lecturer VALUES ('GEOG25', 'Cynthia Quinn', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('COMP26', 'Jerry Evans', 'Computing');
INSERT INTO Lecturer VALUES ('COMP27', 'Paula Hardy', 'Computing');
INSERT INTO Lecturer VALUES ('CENG28', 'Jessica Newman', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PSYC29', 'Barbara Whitaker', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG30', 'Pamela Cunningham', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GEOG31', 'Rebecca Watkins', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL32', 'Jacob Pierce', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CHEM33', 'John Gordon', 'Chemistry');
INSERT INTO Lecturer VALUES ('PSYC34', 'James Mitchell', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG35', 'Maria Cruz', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BMNG36', 'Nathan Collins', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP37', 'Daniel Mejia', 'Computing');
INSERT INTO Lecturer VALUES ('PSYC38', 'Leonard Hess', 'Psychology');
INSERT INTO Lecturer VALUES ('BMNG39', 'Dr. Troy Noble', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHAR40', 'Katherine Cooke', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PSYC41', 'Andrew Garcia', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS42', 'Linda Dunn', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL43', 'Alexandra Case', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL44', 'Jeremy Larsen', 'Biology');
INSERT INTO Lecturer VALUES ('COMP45', 'Jill Lee', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL46', 'Victoria Burton', 'Biology');
INSERT INTO Lecturer VALUES ('GOVN47', 'John Peck', 'Government');
INSERT INTO Lecturer VALUES ('EENG48', 'Austin Jones', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL49', 'Eric Davis', 'Biology');
INSERT INTO Lecturer VALUES ('NURS50', 'Janice Hansen', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL51', 'Barbara Jackson', 'Biology');
INSERT INTO Lecturer VALUES ('SOCI52', 'Shawn Carter', 'Sociology');
INSERT INTO Lecturer VALUES ('GEOG53', 'Jason Cunningham', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GOVN54', 'Adam Chandler', 'Government');
INSERT INTO Lecturer VALUES ('COMP55', 'Mary Spencer', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR56', 'Kelly Turner', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHAR57', 'Carlos Green', 'Pharmacy');
INSERT INTO Lecturer VALUES ('COMP58', 'Albert Morgan', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG59', 'Sandra Galvan', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH60', 'Carol Mills', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL61', 'Justin Hickman MD', 'Life Sciences');
INSERT INTO Lecturer VALUES ('COMP62', 'Andrew Guzman', 'Computing');
INSERT INTO Lecturer VALUES ('MED63', 'Alicia Newman', 'Medicine');
INSERT INTO Lecturer VALUES ('PHAR64', 'Jodi Crane', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG65', 'Stephanie Harris', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHAR66', 'Jeffrey Davis', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI67', 'Laura Young', 'Sociology');
INSERT INTO Lecturer VALUES ('MATH68', 'Leslie Powell', 'Mathematics');
INSERT INTO Lecturer VALUES ('NURS69', 'Shannon Dickson', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL70', 'Gail Butler', 'Biology');
INSERT INTO Lecturer VALUES ('PHYS71', 'Sandra Wagner', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM72', 'Debra Gonzales', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('EPNG73', 'Guy Neal', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC74', 'Kevin Russell', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL75', 'Carrie Jordan', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MATH76', 'Mary Jennings', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL77', 'David Hartman DDS', 'Biology');
INSERT INTO Lecturer VALUES ('PHYS78', 'Deborah Hill', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM79', 'Tina Lee', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL80', 'Eric Woods', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR81', 'Miranda Reed', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI82', 'Katherine Butler', 'Sociology');
INSERT INTO Lecturer VALUES ('PSYC83', 'Julia Delacruz', 'Psychology');
INSERT INTO Lecturer VALUES ('PHAR84', 'Richard Hart', 'Pharmacy');
INSERT INTO Lecturer VALUES ('COMP85', 'Adrian Campbell', 'Computing');
INSERT INTO Lecturer VALUES ('NURS86', 'Stephanie Cantrell', 'Nursing');
INSERT INTO Lecturer VALUES ('COMP87', 'Kenneth Cooper', 'Computing');
INSERT INTO Lecturer VALUES ('COMP88', 'Denise Townsend', 'Computing');
INSERT INTO Lecturer VALUES ('CENG89', 'Christine Bennett', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('ECON90', 'Kenneth Jenkins', 'Economics');
INSERT INTO Lecturer VALUES ('PHYS91', 'Ronald Carpenter', 'Physics');
INSERT INTO Lecturer VALUES ('PHAR92', 'Vanessa Barrett', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MSBM93', 'Kelly Martinez', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CENG94', 'Patrick Carey', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS95', 'Lauren Martinez', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC96', 'Dana Burnett', 'Psychology');
INSERT INTO Lecturer VALUES ('MED97', 'Jason Roman', 'Medicine');
INSERT INTO Lecturer VALUES ('BMNG98', 'George Patterson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CHEM99', 'Matthew Reyes', 'Chemistry');
INSERT INTO Lecturer VALUES ('PSYC100', 'Kylie Patterson', 'Psychology');
INSERT INTO Lecturer VALUES ('PSYC101', 'Ryan Hughes', 'Psychology');
INSERT INTO Lecturer VALUES ('MED102', 'Jennifer Tyler', 'Medicine');
INSERT INTO Lecturer VALUES ('ECON103', 'Erika Adams', 'Economics');
INSERT INTO Lecturer VALUES ('MED104', 'Anna Park', 'Medicine');
INSERT INTO Lecturer VALUES ('PHAR105', 'Mikayla Walker', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG106', 'Samantha Lyons', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CHEM107', 'Casey Jones', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHYS108', 'Colleen Ward', 'Physics');
INSERT INTO Lecturer VALUES ('PHAR109', 'Brian Kelly', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHAR110', 'Richard Cox', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHAR111', 'Troy Hicks', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EPNG112', 'Travis Thomas', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CENG113', 'Mark Garcia', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL114', 'Stephanie Scott', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL115', 'Brian Ponce', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EENG116', 'Patrick Tate', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR117', 'Anthony Swanson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHAR118', 'Jessica Parrish', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI119', 'Charles Spencer', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS120', 'Jordan Reyes', 'Physics');
INSERT INTO Lecturer VALUES ('ECON121', 'Julie Kelley', 'Economics');
INSERT INTO Lecturer VALUES ('PHAR122', 'Gabrielle Parker', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CHEM123', 'Michael Carr', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHYS124', 'Mrs. Jessica Ellis', 'Physics');
INSERT INTO Lecturer VALUES ('NURS125', 'Diane Reeves', 'Nursing');
INSERT INTO Lecturer VALUES ('EENG126', 'Michelle Hayes', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('SOCI127', 'Dennis Figueroa', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL128', 'Melissa Gardner', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CHEM129', 'Chelsea Wilson', 'Chemistry');
INSERT INTO Lecturer VALUES ('BMNG130', 'Keith Mcdaniel', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHYS131', 'Greg Campbell', 'Physics');
INSERT INTO Lecturer VALUES ('MATH132', 'Christine Hardin', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL133', 'Ashley Morse', 'Life Sciences');
INSERT INTO Lecturer VALUES ('COMP134', 'Tammy Cabrera', 'Computing');
INSERT INTO Lecturer VALUES ('NURS135', 'Richard Brown', 'Nursing');
INSERT INTO Lecturer VALUES ('SOCI136', 'Charles Smith', 'Sociology');
INSERT INTO Lecturer VALUES ('CHEM137', 'John Wright', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL138', 'Tiffany Zimmerman', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN139', 'Veronica Barton', 'Government');
INSERT INTO Lecturer VALUES ('CHEM140', 'Bradley Mason', 'Chemistry');
INSERT INTO Lecturer VALUES ('EENG141', 'David Mullen', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHYS142', 'Diana Johnson', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM143', 'Scott Weber', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL144', 'Patrick Stuart', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MED145', 'Lori Henry', 'Medicine');
INSERT INTO Lecturer VALUES ('ECON146', 'Daniel Hamilton', 'Economics');
INSERT INTO Lecturer VALUES ('ECON147', 'David Leon', 'Economics');
INSERT INTO Lecturer VALUES ('GOVN148', 'Lisa Dixon', 'Government');
INSERT INTO Lecturer VALUES ('MATH149', 'Brian Woods', 'Mathematics');
INSERT INTO Lecturer VALUES ('CENG150', 'Miss Amy Kelly', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('ECON151', 'Stephen Gordon', 'Economics');
INSERT INTO Lecturer VALUES ('PHAR152', 'Dr. Jocelyn Ruiz', 'Pharmacy');
INSERT INTO Lecturer VALUES ('NURS153', 'Amy Henderson', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR154', 'John Mason', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CHEM155', 'Molly Mueller', 'Chemistry');
INSERT INTO Lecturer VALUES ('BMNG156', 'Chris Moore', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PSYC157', 'Steven Jordan', 'Psychology');
INSERT INTO Lecturer VALUES ('EENG158', 'Connie Craig', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PSYC159', 'Joseph Crawford III', 'Psychology');
INSERT INTO Lecturer VALUES ('BMNG160', 'Carl Moyer', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EENG161', 'Kenneth Hurley', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('ECON162', 'Julie Jenkins', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG163', 'James Colon', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MSBM164', 'Dr. Mark Mccarthy II', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON165', 'Sandra Ayala', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG166', 'Casey Ruiz', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHYS167', 'Sherri Howard', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL168', 'Bruce Duffy', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL169', 'Kevin Avila', 'Biology');
INSERT INTO Lecturer VALUES ('SOCI170', 'Leslie Brown', 'Sociology');
INSERT INTO Lecturer VALUES ('EENG171', 'Joshua Phelps', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EPNG172', 'Derek Johnson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GEOG173', 'Barbara Cunningham', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('COMP174', 'Angela Miller', 'Computing');
INSERT INTO Lecturer VALUES ('BMNG175', 'Wayne Newton', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MATH176', 'Gail Smith', 'Mathematics');
INSERT INTO Lecturer VALUES ('CHEM177', 'Mary Reyes', 'Chemistry');
INSERT INTO Lecturer VALUES ('BMNG178', 'Mr. Justin Anderson DDS', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GEOG179', 'Madison Compton', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CENG180', 'Kaitlin Parrish', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHAR181', 'Frank Mejia', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PSYC182', 'Sandra Buck', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG183', 'Karen Hill', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CHEM184', 'Melissa Lyons', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL185', 'Alicia Jones', 'Biology');
INSERT INTO Lecturer VALUES ('CENG186', 'John Smith', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHYS187', 'Kyle Smith', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL188', 'Robert Hernandez', 'Biology');
INSERT INTO Lecturer VALUES ('COMP189', 'Gary Johnson', 'Computing');
INSERT INTO Lecturer VALUES ('SOCI190', 'Gloria Chavez', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL191', 'Mr. Walter Thomas', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MATH192', 'Amy Burton', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL193', 'Melissa Mccann', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CHEM194', 'Mackenzie Carpenter', 'Chemistry');
INSERT INTO Lecturer VALUES ('EPNG195', 'Daniel Carey', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG196', 'Brittney Myers', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CENG197', 'Richard Matthews', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHAR198', 'Kaitlyn Rhodes', 'Pharmacy');
INSERT INTO Lecturer VALUES ('COMP199', 'Morgan Moreno', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL200', 'Mary Lawson', 'Biology');
INSERT INTO Lecturer VALUES ('EPNG201', 'Gary Anderson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM202', 'Peter Jones', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL203', 'Jennifer Lee', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MED204', 'Jacob Garrett', 'Medicine');
INSERT INTO Lecturer VALUES ('BMNG205', 'Carmen Harris', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON206', 'Valerie Berger', 'Economics');
INSERT INTO Lecturer VALUES ('ECON207', 'Ryan Carter', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG208', 'Lisa Black', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EPNG209', 'Joshua Thompson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GEOG210', 'Spencer Smith', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHYS211', 'Leonard Perez', 'Physics');
INSERT INTO Lecturer VALUES ('MATH212', 'Elizabeth Murphy', 'Mathematics');
INSERT INTO Lecturer VALUES ('SOCI213', 'Roger Bright', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS214', 'Lisa Myers', 'Physics');
INSERT INTO Lecturer VALUES ('MATH215', 'Linda Perry', 'Mathematics');
INSERT INTO Lecturer VALUES ('GOVN216', 'Angela Horn', 'Government');
INSERT INTO Lecturer VALUES ('CHEM217', 'Keith Ortega', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL218', 'Connie Lee', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MSBM219', 'Michele Woods', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('NURS220', 'Jasmine Smith', 'Nursing');
INSERT INTO Lecturer VALUES ('BMNG221', 'Kelly Thompson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CENG222', 'Jodi Henry', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MSBM223', 'Jennifer George', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED224', 'Alexandria Jones', 'Medicine');
INSERT INTO Lecturer VALUES ('EPNG225', 'David Lam', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('COMP226', 'Nicole Williams', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR227', 'Brian Bonilla', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BMNG228', 'Andrew Grimes', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('SOCI229', 'Kathryn Duarte', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL230', 'Nicole Cooper', 'Biology');
INSERT INTO Lecturer VALUES ('BMNG231', 'Philip Huffman', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PSYC232', 'Donald Larson', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG233', 'Lauren Thomas', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC234', 'Amy Jones', 'Psychology');
INSERT INTO Lecturer VALUES ('MSBM235', 'Vicki Armstrong', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BMNG236', 'Aaron Barnes', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GEOG237', 'Hector Mann', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MED238', 'Cody Bailey', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL239', 'Bryan Chavez', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL240', 'Shannon Dawson', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHYS241', 'Justin Kirk', 'Physics');
INSERT INTO Lecturer VALUES ('GEOG242', 'Alejandro Greer', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CENG243', 'Jacqueline Cummings', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('EENG244', 'Nicole Thomas', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EENG245', 'John Lopez', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL246', 'Nathaniel Jones', 'Biology');
INSERT INTO Lecturer VALUES ('CENG247', 'Amy Williams', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GOVN248', 'Alexis Lynch', 'Government');
INSERT INTO Lecturer VALUES ('EENG249', 'Elizabeth Martin', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHYS250', 'David Santiago', 'Physics');
INSERT INTO Lecturer VALUES ('BMNG251', 'Mr. Christopher Wallace', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON252', 'Monica Diaz', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL253', 'Melissa Stephens', 'Biology');
INSERT INTO Lecturer VALUES ('EENG254', 'Pamela Brown', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GOVN255', 'Mr. Brett Short', 'Government');
INSERT INTO Lecturer VALUES ('CHEM256', 'Jo Miller', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP257', 'Christine Copeland', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL258', 'Jacob Fox', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL259', 'Crystal Webb', 'Biology');
INSERT INTO Lecturer VALUES ('EENG260', 'Natasha Weiss', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHYS261', 'Jerome Rice', 'Physics');
INSERT INTO Lecturer VALUES ('SOCI262', 'Daniel Parker', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON263', 'Monica Mason', 'Economics');
INSERT INTO Lecturer VALUES ('PHAR264', 'Christina Lopez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('ECON265', 'Patricia Myers', 'Economics');
INSERT INTO Lecturer VALUES ('COMP266', 'Michelle Wright', 'Computing');
INSERT INTO Lecturer VALUES ('PSYC267', 'Kevin Phillips', 'Psychology');
INSERT INTO Lecturer VALUES ('GOVN268', 'Jeffrey Davis', 'Government');
INSERT INTO Lecturer VALUES ('MED269', 'Alice Duran', 'Medicine');
INSERT INTO Lecturer VALUES ('MED270', 'Peter Scott', 'Medicine');
INSERT INTO Lecturer VALUES ('EPNG271', 'Linda Moore', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS272', 'Dana Moore', 'Nursing');
INSERT INTO Lecturer VALUES ('EPNG273', 'James Chavez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM274', 'Leah Garcia', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PHYS275', 'Paul Benitez', 'Physics');
INSERT INTO Lecturer VALUES ('EPNG276', 'Anthony Moody', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PHYS277', 'Jonathan Bush', 'Physics');
INSERT INTO Lecturer VALUES ('PSYC278', 'Adam King', 'Psychology');
INSERT INTO Lecturer VALUES ('EENG279', 'Amanda Weber', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM280', 'Vanessa Sharp', 'Chemistry');
INSERT INTO Lecturer VALUES ('BMNG281', 'Tabitha Mayo', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL282', 'Bradley Jackson', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL283', 'Elizabeth Mata', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MATH284', 'Cynthia Aguilar', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHAR285', 'Carlos Ford', 'Pharmacy');
INSERT INTO Lecturer VALUES ('NURS286', 'John Martin', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS287', 'Nicole Sandoval', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL288', 'William Kelly', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PSYC289', 'Scott Price', 'Psychology');
INSERT INTO Lecturer VALUES ('CENG290', 'Erin Mosley', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS291', 'Amanda Cross', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC292', 'Jodi Moody', 'Psychology');
INSERT INTO Lecturer VALUES ('COMP293', 'Peter Moore', 'Computing');
INSERT INTO Lecturer VALUES ('EPNG294', 'Olivia Rodriguez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MED295', 'Joseph Valenzuela', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL296', 'Michael Anthony', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC297', 'Desiree Guzman', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL298', 'Derrick Morrison', 'Biology');
INSERT INTO Lecturer VALUES ('NURS299', 'Paul Terrell', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS300', 'Timothy Turner', 'Nursing');
INSERT INTO Lecturer VALUES ('GOVN301', 'Destiny Campbell', 'Government');
INSERT INTO Lecturer VALUES ('MATH302', 'William Sexton', 'Mathematics');
INSERT INTO Lecturer VALUES ('EENG303', 'Johnny Estrada', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('COMP304', 'Shelly Oliver', 'Computing');
INSERT INTO Lecturer VALUES ('MED305', 'Marcia Rogers', 'Medicine');
INSERT INTO Lecturer VALUES ('GEOG306', 'Megan Bradford', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MED307', 'Miguel Warren', 'Medicine');
INSERT INTO Lecturer VALUES ('MED308', 'Andrew Torres', 'Medicine');
INSERT INTO Lecturer VALUES ('ECON309', 'Jaclyn Jones', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG310', 'Cheryl Martin', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC311', 'James Gentry', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI312', 'Mr. Nicholas Alexander DVM', 'Sociology');
INSERT INTO Lecturer VALUES ('EENG313', 'Paul Campbell', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL314', 'Benjamin Perez', 'Biology');
INSERT INTO Lecturer VALUES ('COMP315', 'Anthony Schwartz', 'Computing');
INSERT INTO Lecturer VALUES ('PSYC316', 'Christopher Rogers', 'Psychology');
INSERT INTO Lecturer VALUES ('ECON317', 'Mrs. Rachel Brown MD', 'Economics');
INSERT INTO Lecturer VALUES ('MSBM318', 'Sarah Yates', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL319', 'James Martin', 'Biology');
INSERT INTO Lecturer VALUES ('PHAR320', 'Danielle Keller', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL321', 'Amy Edwards', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHYS322', 'Robert Hansen', 'Physics');
INSERT INTO Lecturer VALUES ('PHAR323', 'Michelle Williams', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PSYC324', 'Travis Anthony', 'Psychology');
INSERT INTO Lecturer VALUES ('GOVN325', 'Sharon Duncan', 'Government');
INSERT INTO Lecturer VALUES ('EENG326', 'Mrs. Kristin Roberts', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CENG327', 'Joseph Wood', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BMNG328', 'Alan Henderson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG329', 'Pamela Johnson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON330', 'David Pierce', 'Economics');
INSERT INTO Lecturer VALUES ('MED331', 'Laura Richmond', 'Medicine');
INSERT INTO Lecturer VALUES ('PHYS332', 'Brandon Delgado', 'Physics');
INSERT INTO Lecturer VALUES ('PSYC333', 'Stephanie Shelton', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL334', 'George Schroeder MD', 'Biology');
INSERT INTO Lecturer VALUES ('MED335', 'Brett Cole', 'Medicine');
INSERT INTO Lecturer VALUES ('MED336', 'Valerie Shelton', 'Medicine');
INSERT INTO Lecturer VALUES ('PHYS337', 'Michelle Wallace', 'Physics');
INSERT INTO Lecturer VALUES ('COMP338', 'Regina Lopez', 'Computing');
INSERT INTO Lecturer VALUES ('GOVN339', 'Michael Kim PhD', 'Government');
INSERT INTO Lecturer VALUES ('EPNG340', 'Robin Rhodes', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC341', 'Judy Nicholson', 'Psychology');
INSERT INTO Lecturer VALUES ('PHYS342', 'Katie Ward', 'Physics');
INSERT INTO Lecturer VALUES ('PHYS343', 'Kenneth Bauer', 'Physics');
INSERT INTO Lecturer VALUES ('EENG344', 'Alvin Moore', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR345', 'Stacy Frazier', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EENG346', 'Gloria Ray', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL347', 'Ian Jones', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR348', 'Glenn Archer', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GOVN349', 'Donald Lopez', 'Government');
INSERT INTO Lecturer VALUES ('ECON350', 'Jennifer Morton', 'Economics');
INSERT INTO Lecturer VALUES ('MED351', 'Sandra Rose', 'Medicine');
INSERT INTO Lecturer VALUES ('BMNG352', 'Dawn Wilson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHYS353', 'Jordan Campbell', 'Physics');
INSERT INTO Lecturer VALUES ('COMP354', 'Angela Acosta', 'Computing');
INSERT INTO Lecturer VALUES ('PHYS355', 'Lauren Mcdowell', 'Physics');
INSERT INTO Lecturer VALUES ('PHAR356', 'Theresa Long', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG357', 'Seth Clark', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG358', 'Kimberly Miller', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GOVN359', 'Adrian Torres', 'Government');
INSERT INTO Lecturer VALUES ('NURS360', 'Clarence Galloway', 'Nursing');
INSERT INTO Lecturer VALUES ('EPNG361', 'Sara Dennis', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM362', 'James Jackson', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MSBM363', 'Scott Ware', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON364', 'Destiny Compton', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG365', 'John Scott', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP366', 'Zachary Walsh', 'Computing');
INSERT INTO Lecturer VALUES ('NURS367', 'Charles Vasquez', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS368', 'Sarah Carson', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC369', 'Brandi Hopkins', 'Psychology');
INSERT INTO Lecturer VALUES ('CENG370', 'Tiffany Morgan', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED371', 'Gary Jimenez', 'Medicine');
INSERT INTO Lecturer VALUES ('CHEM372', 'Lauren Kirby', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL373', 'Gina Nelson', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PSYC374', 'Tracy Gross', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM375', 'Robin Anderson', 'Chemistry');
INSERT INTO Lecturer VALUES ('CENG376', 'Angela Montgomery', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS377', 'Todd Briggs', 'Nursing');
INSERT INTO Lecturer VALUES ('CENG378', 'Jesse Richards', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHAR379', 'Scott Gonzales', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EPNG380', 'Mary Harrison', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM381', 'Joshua Choi', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('SOCI382', 'Elizabeth Dunn', 'Sociology');
INSERT INTO Lecturer VALUES ('EENG383', 'Roy Brown', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MED384', 'Gerald Weaver', 'Medicine');
INSERT INTO Lecturer VALUES ('CHEM385', 'Jessica Collins', 'Chemistry');
INSERT INTO Lecturer VALUES ('SOCI386', 'Gregory Hill', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS387', 'Mr. Bobby Moore', 'Nursing');
INSERT INTO Lecturer VALUES ('SOCI388', 'Christopher Hogan', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS389', 'Alexis Edwards', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL390', 'Stefanie Smith', 'Biology');
INSERT INTO Lecturer VALUES ('NURS391', 'Samuel Watson', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR392', 'Curtis Anderson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EPNG393', 'Kevin Gutierrez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MATH394', 'Robert Williams', 'Mathematics');
INSERT INTO Lecturer VALUES ('NURS395', 'Shannon Lowe', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR396', 'Jill Sanchez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EPNG397', 'Tammy Evans', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MATH398', 'Madison Perry', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG399', 'Angela Johnson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CHEM400', 'Karla Berg', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHAR401', 'Tanya Chavez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EPNG402', 'Gregory Blankenship', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GOVN403', 'Elizabeth Velasquez', 'Government');
INSERT INTO Lecturer VALUES ('COMP404', 'Alvin Le', 'Computing');
INSERT INTO Lecturer VALUES ('PSYC405', 'Michael Nichols', 'Psychology');
INSERT INTO Lecturer VALUES ('PSYC406', 'John Mullins', 'Psychology');
INSERT INTO Lecturer VALUES ('GOVN407', 'Terry Patton', 'Government');
INSERT INTO Lecturer VALUES ('PHYS408', 'Charles Jackson', 'Physics');
INSERT INTO Lecturer VALUES ('COMP409', 'Ian Chambers', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL410', 'Laurie Griffith', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR411', 'Tammy Ramirez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI412', 'Dr. Brandon Jordan', 'Sociology');
INSERT INTO Lecturer VALUES ('CENG413', 'Ricky Williams', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL414', 'Austin Macias', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PSYC415', 'William Flowers', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS416', 'Roberto Todd', 'Nursing');
INSERT INTO Lecturer VALUES ('PHYS417', 'Joyce Bullock', 'Physics');
INSERT INTO Lecturer VALUES ('CHEM418', 'Michael Blankenship', 'Chemistry');
INSERT INTO Lecturer VALUES ('PSYC419', 'Ariana Williams', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM420', 'Leroy Hansen', 'Chemistry');
INSERT INTO Lecturer VALUES ('SOCI421', 'Grace Marquez', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS422', 'Shane Valdez', 'Nursing');
INSERT INTO Lecturer VALUES ('EPNG423', 'Cassidy Garcia', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CHEM424', 'Gregory Johnson', 'Chemistry');
INSERT INTO Lecturer VALUES ('NURS425', 'Rachel Watts', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC426', 'Brian Moran', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL427', 'Samuel Williams', 'Biology');
INSERT INTO Lecturer VALUES ('EPNG428', 'Joy Horne', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BMNG429', 'Ricky Gonzalez DDS', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP430', 'Tina Marshall', 'Computing');
INSERT INTO Lecturer VALUES ('BMNG431', 'Rebecca Pace', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON432', 'Tracy Wilson', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL433', 'Michael Johnson', 'Biology');
INSERT INTO Lecturer VALUES ('GOVN434', 'Joseph Williams', 'Government');
INSERT INTO Lecturer VALUES ('COMP435', 'Matthew Rodriguez', 'Computing');
INSERT INTO Lecturer VALUES ('ECON436', 'Theresa Wade', 'Economics');
INSERT INTO Lecturer VALUES ('PHAR437', 'Cory James', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PSYC438', 'Kimberly Green', 'Psychology');
INSERT INTO Lecturer VALUES ('PHAR439', 'Suzanne Howell', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MATH440', 'Kristin Cruz', 'Mathematics');
INSERT INTO Lecturer VALUES ('MSBM441', 'Anthony Guerrero', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BMNG442', 'Matthew Thomas', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GOVN443', 'Ronald Harrison', 'Government');
INSERT INTO Lecturer VALUES ('GEOG444', 'Leslie Howard', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('NURS445', 'Brittany Bradford', 'Nursing');
INSERT INTO Lecturer VALUES ('ECON446', 'Kathleen Foster', 'Economics');
INSERT INTO Lecturer VALUES ('MED447', 'Jordan White', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC448', 'William Webb', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI449', 'Cynthia Torres', 'Sociology');
INSERT INTO Lecturer VALUES ('CENG450', 'Crystal Black', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('EENG451', 'Devin Arellano', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MATH452', 'Gary Flores', 'Mathematics');
INSERT INTO Lecturer VALUES ('CHEM453', 'James Elliott', 'Chemistry');
INSERT INTO Lecturer VALUES ('CHEM454', 'William Skinner', 'Chemistry');
INSERT INTO Lecturer VALUES ('CHEM455', 'Amber Silva', 'Chemistry');
INSERT INTO Lecturer VALUES ('CENG456', 'Sheryl Nguyen', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS457', 'Brett Jordan', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL458', 'Diana Dillon', 'Biology');
INSERT INTO Lecturer VALUES ('EENG459', 'Eric Salinas', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MSBM460', 'Rebecca Garcia', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PSYC461', 'Andrew Torres', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM462', 'Jessica Richardson', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL463', 'Reginald Jordan', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR464', 'John Bass', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED465', 'Jessica Hamilton', 'Medicine');
INSERT INTO Lecturer VALUES ('CHEM466', 'Thomas Fleming V', 'Chemistry');
INSERT INTO Lecturer VALUES ('NURS467', 'Jamie Mcmillan', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC468', 'Amanda Harrington', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG469', 'Sara Boyd', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BIOL470', 'Wayne Lam', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC471', 'Stephanie Chavez', 'Psychology');
INSERT INTO Lecturer VALUES ('MATH472', 'Donna Olson', 'Mathematics');
INSERT INTO Lecturer VALUES ('SOCI473', 'Curtis Morton', 'Sociology');
INSERT INTO Lecturer VALUES ('CHEM474', 'Denise Thomas', 'Chemistry');
INSERT INTO Lecturer VALUES ('NURS475', 'Angela Hahn', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS476', 'Grace Smith', 'Nursing');
INSERT INTO Lecturer VALUES ('GOVN477', 'Kara Wilson', 'Government');
INSERT INTO Lecturer VALUES ('COMP478', 'Destiny Holmes', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG479', 'Brittany Parker', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PSYC480', 'Casey Stephens', 'Psychology');
INSERT INTO Lecturer VALUES ('PHYS481', 'Christine Perry', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL482', 'Timothy Morrison', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL483', 'Joshua Sanders', 'Biology');
INSERT INTO Lecturer VALUES ('BMNG484', 'Kevin Anderson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EENG485', 'Jeffery Kelly', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR486', 'David Wilson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CENG487', 'Sherry Thornton', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS488', 'Deborah Powers', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS489', 'Ashley Garcia', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC490', 'Luis Stewart', 'Psychology');
INSERT INTO Lecturer VALUES ('MED491', 'John Waters', 'Medicine');
INSERT INTO Lecturer VALUES ('MED492', 'Mr. Kevin Baird', 'Medicine');
INSERT INTO Lecturer VALUES ('GOVN493', 'Kyle Smith', 'Government');
INSERT INTO Lecturer VALUES ('PHYS494', 'Diana Kline', 'Physics');
INSERT INTO Lecturer VALUES ('PHYS495', 'Linda Steele', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM496', 'Dawn Contreras', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BMNG497', 'Dana Willis', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GEOG498', 'David Jones', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('NURS499', 'Sherry Baxter', 'Nursing');
INSERT INTO Lecturer VALUES ('GEOG500', 'Robert Combs', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHYS501', 'Michael Collins', 'Physics');
INSERT INTO Lecturer VALUES ('EPNG502', 'Kenneth Short', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EENG503', 'Christopher West', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('COMP504', 'Brian Mcguire PhD', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR505', 'Megan Myers', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CENG506', 'Patricia Woods', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CENG507', 'Alexandra Jones', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GEOG508', 'Victor Conway', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHYS509', 'Jessica Stokes', 'Physics');
INSERT INTO Lecturer VALUES ('MED510', 'Erica Cabrera', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC511', 'Raymond Martin', 'Psychology');
INSERT INTO Lecturer VALUES ('MED512', 'James Bradley DDS', 'Medicine');
INSERT INTO Lecturer VALUES ('NURS513', 'Dana Griffin', 'Nursing');
INSERT INTO Lecturer VALUES ('BMNG514', 'Walter Mckinney', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CHEM515', 'Summer Jones', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHYS516', 'Stephen Poole', 'Physics');
INSERT INTO Lecturer VALUES ('BMNG517', 'Andrew Manning', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG518', 'Tanya Murphy', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG519', 'Johnathan Ward', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CHEM520', 'Shelby Chambers', 'Chemistry');
INSERT INTO Lecturer VALUES ('GEOG521', 'Nicholas Faulkner', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG522', 'Victoria Cain', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BMNG523', 'Marissa Smith', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL524', 'Veronica Lewis', 'Biology');
INSERT INTO Lecturer VALUES ('MSBM525', 'Laura Lee', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('EENG526', 'Kristi Drake DDS', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EENG527', 'Steven Rice', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM528', 'Holly Miller', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL529', 'Paula Anderson', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC530', 'Jonathan Velazquez', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM531', 'Debbie Mora MD', 'Chemistry');
INSERT INTO Lecturer VALUES ('CHEM532', 'Reginald Peck', 'Chemistry');
INSERT INTO Lecturer VALUES ('EENG533', 'Joseph Patterson', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MATH534', 'Timothy Newton', 'Mathematics');
INSERT INTO Lecturer VALUES ('BMNG535', 'Michael Chandler', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GEOG536', 'Ashley Ochoa', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PSYC537', 'Scott Chavez', 'Psychology');
INSERT INTO Lecturer VALUES ('MATH538', 'Donald Miller', 'Mathematics');
INSERT INTO Lecturer VALUES ('CHEM539', 'Nicole Clark', 'Chemistry');
INSERT INTO Lecturer VALUES ('GOVN540', 'Tammie Harris', 'Government');
INSERT INTO Lecturer VALUES ('EPNG541', 'Holly Allen', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GEOG542', 'Lori Cameron', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('NURS543', 'Stephen Conrad', 'Nursing');
INSERT INTO Lecturer VALUES ('CHEM544', 'Christopher Jones', 'Chemistry');
INSERT INTO Lecturer VALUES ('BMNG545', 'David Oliver', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG546', 'Katherine Williams', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHYS547', 'Paul Taylor', 'Physics');
INSERT INTO Lecturer VALUES ('EPNG548', 'Nicole Kelley', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EENG549', 'Katherine Williams', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR550', 'Sydney Perkins', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG551', 'Ms. Samantha Strong', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EENG552', 'Debbie Contreras', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHYS553', 'Jose Allen', 'Physics');
INSERT INTO Lecturer VALUES ('CHEM554', 'Casey Gordon', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL555', 'Matthew Carter', 'Biology');
INSERT INTO Lecturer VALUES ('EENG556', 'Elizabeth Bishop', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PSYC557', 'William Mcbride', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI558', 'Mary Dickson', 'Sociology');
INSERT INTO Lecturer VALUES ('CENG559', 'Krystal Castillo', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS560', 'Renee Garcia', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS561', 'Darrell Humphrey', 'Nursing');
INSERT INTO Lecturer VALUES ('ECON562', 'Christine Strickland', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG563', 'Dennis Hall', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('NURS564', 'Mark Castillo', 'Nursing');
INSERT INTO Lecturer VALUES ('EENG565', 'Susan Sanchez', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MATH566', 'Stephen Wells', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL567', 'Aaron Harris', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC568', 'Erin Hill', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL569', 'Charlotte Bell', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GEOG570', 'Thomas Wright', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHYS571', 'Abigail Brooks', 'Physics');
INSERT INTO Lecturer VALUES ('MED572', 'William Ball', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC573', 'Matthew Guerrero', 'Psychology');
INSERT INTO Lecturer VALUES ('MED574', 'Martha Frederick', 'Medicine');
INSERT INTO Lecturer VALUES ('MSBM575', 'Ryan Coleman', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('COMP576', 'Todd Oneal', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL577', 'Ashley Lopez', 'Biology');
INSERT INTO Lecturer VALUES ('EENG578', 'Edwin Scott', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('COMP579', 'Stephanie Blanchard', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG580', 'Ann Joseph', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG581', 'Steven Gonzalez', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GOVN582', 'Jessica Daniels', 'Government');
INSERT INTO Lecturer VALUES ('NURS583', 'Christopher Strickland', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS584', 'Emily Smith', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC585', 'Allen Meyer', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG586', 'Troy Hill', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC587', 'Leah Gonzalez', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL588', 'Brian Martinez', 'Biology');
INSERT INTO Lecturer VALUES ('BMNG589', 'Samuel Curry', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG590', 'Jacob Howe', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL591', 'John Caldwell', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL592', 'Todd Dunn', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR593', 'Sharon Burton', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CENG594', 'Dean Bird', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MSBM595', 'Michael Bird', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL596', 'Todd Hart', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR597', 'Debbie Cisneros', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EENG598', 'Daniel Bradley', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL599', 'Adam Garcia', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CHEM600', 'Adam Parker', 'Chemistry');
INSERT INTO Lecturer VALUES ('GOVN601', 'Benjamin Foster', 'Government');
INSERT INTO Lecturer VALUES ('SOCI602', 'Tracy Smith', 'Sociology');
INSERT INTO Lecturer VALUES ('GEOG603', 'Reginald Meadows', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('COMP604', 'Rebekah Watson', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR605', 'Jason Baker', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI606', 'Tony Sanchez', 'Sociology');
INSERT INTO Lecturer VALUES ('SOCI607', 'Eric Mays', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS608', 'Shawn Winters', 'Nursing');
INSERT INTO Lecturer VALUES ('CHEM609', 'Erik Diaz', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL610', 'Brent Garcia', 'Biology');
INSERT INTO Lecturer VALUES ('MATH611', 'Maria Gonzalez', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL612', 'Megan Anderson', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN613', 'Whitney Banks', 'Government');
INSERT INTO Lecturer VALUES ('MATH614', 'Laura Garcia', 'Mathematics');
INSERT INTO Lecturer VALUES ('NURS615', 'Amanda Miller', 'Nursing');
INSERT INTO Lecturer VALUES ('ECON616', 'Michelle Harris', 'Economics');
INSERT INTO Lecturer VALUES ('EENG617', 'Kevin Pierce', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PSYC618', 'Pamela Henson', 'Psychology');
INSERT INTO Lecturer VALUES ('CENG619', 'David King', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MSBM620', 'Holly Allen', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL621', 'Sonia Jones', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL622', 'Brandon Lewis', 'Life Sciences');
INSERT INTO Lecturer VALUES ('NURS623', 'Patricia Ramirez', 'Nursing');
INSERT INTO Lecturer VALUES ('SOCI624', 'Joshua Alvarez', 'Sociology');
INSERT INTO Lecturer VALUES ('MSBM625', 'Linda Love', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON626', 'James Anderson', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG627', 'David Richard', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG628', 'Tina Thompson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG629', 'Tony Ray', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS630', 'Eric Ramirez', 'Nursing');
INSERT INTO Lecturer VALUES ('GOVN631', 'Alec Allen PhD', 'Government');
INSERT INTO Lecturer VALUES ('PSYC632', 'Juan Camacho', 'Psychology');
INSERT INTO Lecturer VALUES ('MED633', 'Veronica Garner', 'Medicine');
INSERT INTO Lecturer VALUES ('COMP634', 'Alexander Martin', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG635', 'Blake Bean', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GOVN636', 'Victoria Wells', 'Government');
INSERT INTO Lecturer VALUES ('GEOG637', 'Amy Francis', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GOVN638', 'Andre Powell', 'Government');
INSERT INTO Lecturer VALUES ('PSYC639', 'Aaron Santos', 'Psychology');
INSERT INTO Lecturer VALUES ('ECON640', 'Andrew Price', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC641', 'Raymond Austin', 'Psychology');
INSERT INTO Lecturer VALUES ('BMNG642', 'Joseph Gonzalez', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP643', 'Sharon Elliott', 'Computing');
INSERT INTO Lecturer VALUES ('EPNG644', 'Eric Nguyen', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM645', 'Anthony Hobbs', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('GEOG646', 'Jessica Marsh', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('ECON647', 'Eugene Johnson', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG648', 'Sydney Morrison', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('NURS649', 'Jennifer Cobb', 'Nursing');
INSERT INTO Lecturer VALUES ('EPNG650', 'Chelsey Bell', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS651', 'Michael Myers', 'Nursing');
INSERT INTO Lecturer VALUES ('COMP652', 'Michael Singh', 'Computing');
INSERT INTO Lecturer VALUES ('ECON653', 'Eric Hicks', 'Economics');
INSERT INTO Lecturer VALUES ('CENG654', 'Richard Garcia', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('SOCI655', 'Ashley Griffin', 'Sociology');
INSERT INTO Lecturer VALUES ('MED656', 'Donald Morris', 'Medicine');
INSERT INTO Lecturer VALUES ('PHYS657', 'Timothy Burton', 'Physics');
INSERT INTO Lecturer VALUES ('GOVN658', 'William Houston', 'Government');
INSERT INTO Lecturer VALUES ('BIOL659', 'Kathy Watson', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EENG660', 'Manuel Barrett', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CENG661', 'Melissa Wilson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CHEM662', 'Cassandra Leblanc', 'Chemistry');
INSERT INTO Lecturer VALUES ('GOVN663', 'Tamara Austin', 'Government');
INSERT INTO Lecturer VALUES ('GOVN664', 'Stephen Perkins', 'Government');
INSERT INTO Lecturer VALUES ('PSYC665', 'Erin Lloyd', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM666', 'Ryan Simmons', 'Chemistry');
INSERT INTO Lecturer VALUES ('GEOG667', 'Nicholas Porter', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHYS668', 'Denise Dominguez', 'Physics');
INSERT INTO Lecturer VALUES ('CENG669', 'Megan Jones', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED670', 'Lori Matthews', 'Medicine');
INSERT INTO Lecturer VALUES ('PHYS671', 'Angela Vazquez', 'Physics');
INSERT INTO Lecturer VALUES ('EENG672', 'Timothy Coleman', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL673', 'Victoria Hahn', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL674', 'Peter Richards', 'Biology');
INSERT INTO Lecturer VALUES ('EENG675', 'Mark Carter', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MED676', 'Lucas Maldonado', 'Medicine');
INSERT INTO Lecturer VALUES ('NURS677', 'Kevin Hahn', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL678', 'Don Taylor', 'Biology');
INSERT INTO Lecturer VALUES ('MSBM679', 'Emily Stokes', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CHEM680', 'Jacob Russell', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL681', 'Deborah Brewer', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EPNG682', 'Diana Collins', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG683', 'Sean Ramirez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BIOL684', 'Frederick Roy', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL685', 'Laura Hebert', 'Biology');
INSERT INTO Lecturer VALUES ('GOVN686', 'Nicolas Michael', 'Government');
INSERT INTO Lecturer VALUES ('ECON687', 'Brianna Williams', 'Economics');
INSERT INTO Lecturer VALUES ('ECON688', 'Amy Anderson', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC689', 'Alexis Thomas', 'Psychology');
INSERT INTO Lecturer VALUES ('MED690', 'Richard Brock', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC691', 'Eileen Ramsey', 'Psychology');
INSERT INTO Lecturer VALUES ('PSYC692', 'Linda Wilson', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS693', 'Larry Hernandez', 'Nursing');
INSERT INTO Lecturer VALUES ('EPNG694', 'Micheal Schwartz', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PHAR695', 'Jeffery Richards', 'Pharmacy');
INSERT INTO Lecturer VALUES ('ECON696', 'Katie Nielsen', 'Economics');
INSERT INTO Lecturer VALUES ('PHYS697', 'Jeffrey Rojas', 'Physics');
INSERT INTO Lecturer VALUES ('NURS698', 'Steven Russell', 'Nursing');
INSERT INTO Lecturer VALUES ('ECON699', 'Terry Erickson', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG700', 'Dawn Scott', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PHAR701', 'Ann Ellis', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EPNG702', 'Christopher Rice', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('COMP703', 'Marcus Romero', 'Computing');
INSERT INTO Lecturer VALUES ('MED704', 'Joseph Smith', 'Medicine');
INSERT INTO Lecturer VALUES ('EENG705', 'Jason Kim', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CENG706', 'Janet Pitts', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('ECON707', 'John Smith', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC708', 'Jon Anderson', 'Psychology');
INSERT INTO Lecturer VALUES ('PHYS709', 'Richard Rogers', 'Physics');
INSERT INTO Lecturer VALUES ('NURS710', 'Jamie Walsh', 'Nursing');
INSERT INTO Lecturer VALUES ('COMP711', 'John Mack', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL712', 'Karen Wheeler', 'Biology');
INSERT INTO Lecturer VALUES ('ECON713', 'Wendy Stevenson', 'Economics');
INSERT INTO Lecturer VALUES ('NURS714', 'Laurie Frazier', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH715', 'Susan Moreno', 'Mathematics');
INSERT INTO Lecturer VALUES ('GOVN716', 'Patrick Gordon', 'Government');
INSERT INTO Lecturer VALUES ('ECON717', 'David Turner', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL718', 'Steven Davis', 'Biology');
INSERT INTO Lecturer VALUES ('PHAR719', 'Michelle Williams', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MATH720', 'Jamie Jensen', 'Mathematics');
INSERT INTO Lecturer VALUES ('MED721', 'Mary Wilson', 'Medicine');
INSERT INTO Lecturer VALUES ('GEOG722', 'Andrea Burton', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('NURS723', 'Daniel Smith', 'Nursing');
INSERT INTO Lecturer VALUES ('EPNG724', 'Brian Swanson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GOVN725', 'Christopher Wilkerson', 'Government');
INSERT INTO Lecturer VALUES ('BIOL726', 'Jessica Huffman DDS', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN727', 'Martha Lawson', 'Government');
INSERT INTO Lecturer VALUES ('PHYS728', 'Suzanne Farley', 'Physics');
INSERT INTO Lecturer VALUES ('ECON729', 'Benjamin Davis', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG730', 'John Davila', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MED731', 'Christy Lewis', 'Medicine');
INSERT INTO Lecturer VALUES ('BMNG732', 'Christopher Butler', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHAR733', 'Victoria Collier', 'Pharmacy');
INSERT INTO Lecturer VALUES ('NURS734', 'Zachary Ortiz', 'Nursing');
INSERT INTO Lecturer VALUES ('ECON735', 'Jacob Harris', 'Economics');
INSERT INTO Lecturer VALUES ('MSBM736', 'Kyle Cummings', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED737', 'Kimberly Ferguson', 'Medicine');
INSERT INTO Lecturer VALUES ('PHAR738', 'Sara Dawson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI739', 'Lauren Love', 'Sociology');
INSERT INTO Lecturer VALUES ('GOVN740', 'Brent Garcia', 'Government');
INSERT INTO Lecturer VALUES ('COMP741', 'Mathew Gonzalez', 'Computing');
INSERT INTO Lecturer VALUES ('PSYC742', 'Madeline Cline', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL743', 'Tammy Allen', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL744', 'Lisa Terrell', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL745', 'Ronald Chavez', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EPNG746', 'Sarah Gill', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('SOCI747', 'Amy Hill', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON748', 'Larry Porter', 'Economics');
INSERT INTO Lecturer VALUES ('MATH749', 'Kayla Steele', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON750', 'Jamie Torres', 'Economics');

