USE OURVLECloneDatabase;
TRUNCATE TABLE Lecturer;

 ──── Lecturers ────────────────────────────────────────────────────────────────────
INSERT INTO Lecturer VALUES ('CENG1', 'Anna Travis', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PSYC2', 'Jason Taylor', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM3', 'Raymond Middleton', 'Chemistry');
INSERT INTO Lecturer VALUES ('PSYC4', 'Tami Collier', 'Psychology');
INSERT INTO Lecturer VALUES ('MED5', 'Amy King', 'Medicine');
INSERT INTO Lecturer VALUES ('PHAR6', 'Tonya Keller', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED7', 'Joshua Stanley', 'Medicine');
INSERT INTO Lecturer VALUES ('BMNG8', 'Donna Carter', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EENG9', 'Nicole Gonzalez MD', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR10', 'Nicole King', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG11', 'Diamond Horton', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH12', 'Angel Pearson', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON13', 'Nathan Harris', 'Economics');
INSERT INTO Lecturer VALUES ('ECON14', 'Mark Larson', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL15', 'William Murphy', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL16', 'Steven Coleman MD', 'Biology');
INSERT INTO Lecturer VALUES ('MED17', 'John Wallace', 'Medicine');
INSERT INTO Lecturer VALUES ('EPNG18', 'Colleen Ingram MD', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BMNG19', 'Brenda Singleton', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EENG20', 'Alicia Jones', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EPNG21', 'Todd Williamson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EENG22', 'Sean Barker', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GOVN23', 'Krista Moody', 'Government');
INSERT INTO Lecturer VALUES ('MSBM24', 'Abigail Johnson', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('COMP25', 'Wyatt Castro', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG26', 'Frank Roman', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('ECON27', 'Cynthia Edwards', 'Economics');
INSERT INTO Lecturer VALUES ('GEOG28', 'Michael White', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH29', 'Regina Jones', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL30', 'Willie Walker', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC31', 'Karen Snyder', 'Psychology');
INSERT INTO Lecturer VALUES ('ECON32', 'James Ochoa', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL33', 'Dalton Davis', 'Biology');
INSERT INTO Lecturer VALUES ('GOVN34', 'Christie Hutchinson', 'Government');
INSERT INTO Lecturer VALUES ('CHEM35', 'Crystal Morris', 'Chemistry');
INSERT INTO Lecturer VALUES ('MSBM36', 'Karina Ellis', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL37', 'Casey Rivera', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CENG38', 'Mason Gentry', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BMNG39', 'Kimberly Wood', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('SOCI40', 'Marcus Ford', 'Sociology');
INSERT INTO Lecturer VALUES ('GEOG41', 'Paul Noble', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG42', 'Jason Phillips', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('NURS43', 'Lisa Willis', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH44', 'Melissa Johnson', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL45', 'Nicole Morgan', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC46', 'Kelly Alexander', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI47', 'Shane Moore', 'Sociology');
INSERT INTO Lecturer VALUES ('CHEM48', 'Robert Winters', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH49', 'April Rodriguez', 'Mathematics');
INSERT INTO Lecturer VALUES ('SOCI50', 'Robert Cabrera', 'Sociology');
INSERT INTO Lecturer VALUES ('MATH51', 'Sydney Miller', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL52', 'Mr. Theodore Morris DDS', 'Biology');
INSERT INTO Lecturer VALUES ('COMP53', 'Krista Adams', 'Computing');
INSERT INTO Lecturer VALUES ('EPNG54', 'Ashley Cox', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CHEM55', 'Lisa Shelton', 'Chemistry');
INSERT INTO Lecturer VALUES ('BMNG56', 'Dr. Derek Williams PhD', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GEOG57', 'Leslie Hanna', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CHEM58', 'Justin Ferguson', 'Chemistry');
INSERT INTO Lecturer VALUES ('CENG59', 'Jennifer Kelly', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MSBM60', 'Samantha Duran', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON61', 'Becky Johnston', 'Economics');
INSERT INTO Lecturer VALUES ('MED62', 'Brian Horne', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL63', 'Mark Ford', 'Biology');
INSERT INTO Lecturer VALUES ('NURS64', 'Richard Walters', 'Nursing');
INSERT INTO Lecturer VALUES ('CENG65', 'Mark White', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL66', 'Amanda Howard', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CENG67', 'Monica Dickerson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHAR68', 'James Jones', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MSBM69', 'Mark Frost', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('COMP70', 'Adam Gonzalez', 'Computing');
INSERT INTO Lecturer VALUES ('MED71', 'Timothy Thompson', 'Medicine');
INSERT INTO Lecturer VALUES ('MATH72', 'Eric Christian', 'Mathematics');
INSERT INTO Lecturer VALUES ('NURS73', 'Elizabeth Williams', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH74', 'Patrick Conley', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHAR75', 'Oscar Williams', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MATH76', 'Hannah Odonnell', 'Mathematics');
INSERT INTO Lecturer VALUES ('MATH77', 'Ashley Malone', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL78', 'Rachel Reeves', 'Biology');
INSERT INTO Lecturer VALUES ('GEOG79', 'Paul Hughes', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG80', 'Brandy Hicks', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PHYS81', 'Joseph Morris', 'Physics');
INSERT INTO Lecturer VALUES ('NURS82', 'John Hughes', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH83', 'Philip Harris', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHAR84', 'Jennifer Martinez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CHEM85', 'Joshua Cline', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP86', 'Johnny Hill', 'Computing');
INSERT INTO Lecturer VALUES ('EPNG87', 'Christopher Parker', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PHAR88', 'Jonathan Watkins', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GOVN89', 'Lisa Bass', 'Government');
INSERT INTO Lecturer VALUES ('CHEM90', 'Lauren Vargas', 'Chemistry');
INSERT INTO Lecturer VALUES ('GEOG91', 'Jennifer Aguilar', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BMNG92', 'Dr. Kimberly Lopez', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP93', 'Raymond Conrad', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL94', 'Jimmy Miles', 'Biology');
INSERT INTO Lecturer VALUES ('MSBM95', 'Matthew Whitaker', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED96', 'Michael Torres', 'Medicine');
INSERT INTO Lecturer VALUES ('PHYS97', 'Jared Collier', 'Physics');
INSERT INTO Lecturer VALUES ('CENG98', 'Mark Turner', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CHEM99', 'Christian Hodges', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL100', 'Don Larsen', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GEOG101', 'Laura Bennett', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BMNG102', 'Matthew Olson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GOVN103', 'Anna Brown', 'Government');
INSERT INTO Lecturer VALUES ('EENG104', 'Laura Castaneda', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR105', 'Jasmine Thomas', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CHEM106', 'Jonathan Walsh', 'Chemistry');
INSERT INTO Lecturer VALUES ('ECON107', 'Justin Carrillo', 'Economics');
INSERT INTO Lecturer VALUES ('CENG108', 'Jerry Cain', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED109', 'Jacqueline Blevins', 'Medicine');
INSERT INTO Lecturer VALUES ('EENG110', 'Sheila Rodriguez', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('NURS111', 'Vanessa Wells', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS112', 'Mr. Zachary Wade', 'Nursing');
INSERT INTO Lecturer VALUES ('CHEM113', 'Cory Bird', 'Chemistry');
INSERT INTO Lecturer VALUES ('EENG114', 'Laurie Johns', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MATH115', 'Megan Jones', 'Mathematics');
INSERT INTO Lecturer VALUES ('CENG116', 'Cody Johnson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GOVN117', 'Samantha West', 'Government');
INSERT INTO Lecturer VALUES ('GOVN118', 'Rita Palmer', 'Government');
INSERT INTO Lecturer VALUES ('EPNG119', 'Shelby Rivera', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PHAR120', 'Richard Freeman', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED121', 'Richard Villarreal', 'Medicine');
INSERT INTO Lecturer VALUES ('MATH122', 'Julia Anderson', 'Mathematics');
INSERT INTO Lecturer VALUES ('EENG123', 'Deanna Duke', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR124', 'Elizabeth Williams', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EPNG125', 'Kyle Rodriguez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('ECON126', 'Kayla Tran', 'Economics');
INSERT INTO Lecturer VALUES ('MSBM127', 'Mary Barber', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PHYS128', 'Matthew Guerrero', 'Physics');
INSERT INTO Lecturer VALUES ('MED129', 'Darlene Morse', 'Medicine');
INSERT INTO Lecturer VALUES ('COMP130', 'Joanne Smith', 'Computing');
INSERT INTO Lecturer VALUES ('COMP131', 'Jasmine Brown', 'Computing');
INSERT INTO Lecturer VALUES ('CHEM132', 'John Daniels', 'Chemistry');
INSERT INTO Lecturer VALUES ('GEOG133', 'Gregory White', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('ECON134', 'James Baker', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL135', 'Belinda Holloway', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL136', 'Keith Manning', 'Biology');
INSERT INTO Lecturer VALUES ('MED137', 'Natasha Waller', 'Medicine');
INSERT INTO Lecturer VALUES ('NURS138', 'Breanna Costa', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR139', 'Teresa Collins', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BMNG140', 'Sharon Dixon', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EPNG141', 'Susan Church', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BIOL142', 'John Noble', 'Biology');
INSERT INTO Lecturer VALUES ('BMNG143', 'Amber Jones', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL144', 'Bianca Curry', 'Life Sciences');
INSERT INTO Lecturer VALUES ('ECON145', 'Stephanie Jackson', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG146', 'Emily Ingram', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHAR147', 'Christopher Oconnor', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BMNG148', 'Samuel Mosley', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL149', 'John Duke', 'Biology');
INSERT INTO Lecturer VALUES ('MSBM150', 'Matthew Lloyd', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PHAR151', 'Megan Walker', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED152', 'Christina Holt', 'Medicine');
INSERT INTO Lecturer VALUES ('CENG153', 'Isabel Gray', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS154', 'Cheryl Harris', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS155', 'Susan Lawrence', 'Nursing');
INSERT INTO Lecturer VALUES ('MED156', 'Thomas Schneider', 'Medicine');
INSERT INTO Lecturer VALUES ('BMNG157', 'Sara Simpson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MATH158', 'James Gibson', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHYS159', 'Becky Hess', 'Physics');
INSERT INTO Lecturer VALUES ('BMNG160', 'Kelsey Watkins', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PSYC161', 'John Mack', 'Psychology');
INSERT INTO Lecturer VALUES ('BMNG162', 'Jason Osborn', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EENG163', 'Andrew Deleon', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PSYC164', 'Zachary Edwards', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM165', 'Rebecca Spence', 'Chemistry');
INSERT INTO Lecturer VALUES ('CHEM166', 'Crystal Woods', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH167', 'Kathleen Davis', 'Mathematics');
INSERT INTO Lecturer VALUES ('EENG168', 'Laura Pratt', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GEOG169', 'Daniel Macdonald', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL170', 'Christopher Wright', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN171', 'Dana Kelley', 'Government');
INSERT INTO Lecturer VALUES ('SOCI172', 'Cynthia Wyatt', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS173', 'Corey Chen', 'Physics');
INSERT INTO Lecturer VALUES ('BMNG174', 'Jason Burke', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CHEM175', 'Amanda Reed', 'Chemistry');
INSERT INTO Lecturer VALUES ('ECON176', 'Cynthia Mclean', 'Economics');
INSERT INTO Lecturer VALUES ('MATH177', 'Lindsay Ryan', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON178', 'Karla Edwards', 'Economics');
INSERT INTO Lecturer VALUES ('SOCI179', 'Tonya Jones', 'Sociology');
INSERT INTO Lecturer VALUES ('PHAR180', 'Zachary Taylor', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CENG181', 'Mr. Frank Mathis', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GOVN182', 'Mary Nguyen', 'Government');
INSERT INTO Lecturer VALUES ('BMNG183', 'Stephen Herrera', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL184', 'Ronnie Peterson', 'Life Sciences');
INSERT INTO Lecturer VALUES ('COMP185', 'Monica Moore', 'Computing');
INSERT INTO Lecturer VALUES ('EPNG186', 'Stephen Bell', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG187', 'Teresa Lopez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MED188', 'Carolyn Wright', 'Medicine');
INSERT INTO Lecturer VALUES ('MATH189', 'Clinton Rodriguez', 'Mathematics');
INSERT INTO Lecturer VALUES ('PSYC190', 'Christy Clayton', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL191', 'April Barker', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL192', 'Paula Carr', 'Biology');
INSERT INTO Lecturer VALUES ('GOVN193', 'Patricia Bauer', 'Government');
INSERT INTO Lecturer VALUES ('MED194', 'Andrew Hartman', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC195', 'Robert Jimenez', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS196', 'Garrett Petersen', 'Nursing');
INSERT INTO Lecturer VALUES ('MED197', 'Anne Russell', 'Medicine');
INSERT INTO Lecturer VALUES ('PHYS198', 'Kevin Price', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM199', 'Sarah Wells', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PSYC200', 'Daniel Phillips', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL201', 'Jamie Hicks', 'Life Sciences');
INSERT INTO Lecturer VALUES ('ECON202', 'Jamie Park', 'Economics');
INSERT INTO Lecturer VALUES ('COMP203', 'Crystal Brown', 'Computing');
INSERT INTO Lecturer VALUES ('GOVN204', 'Courtney Allen', 'Government');
INSERT INTO Lecturer VALUES ('EENG205', 'Melanie Lane', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('NURS206', 'Debra Roberts', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL207', 'Steven Hood', 'Biology');
INSERT INTO Lecturer VALUES ('COMP208', 'Margaret Miller', 'Computing');
INSERT INTO Lecturer VALUES ('MATH209', 'Monica Goodman', 'Mathematics');
INSERT INTO Lecturer VALUES ('CHEM210', 'Thomas Hurst', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP211', 'Steven Christensen', 'Computing');
INSERT INTO Lecturer VALUES ('BMNG212', 'Dr. Savannah Powers', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON213', 'Benjamin Brock', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG214', 'Paul Williams', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MED215', 'Makayla Porter', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL216', 'Crystal Casey', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MATH217', 'Chase Bailey', 'Mathematics');
INSERT INTO Lecturer VALUES ('MED218', 'Joseph Garcia', 'Medicine');
INSERT INTO Lecturer VALUES ('SOCI219', 'Timothy Gutierrez', 'Sociology');
INSERT INTO Lecturer VALUES ('EENG220', 'Timothy Williams', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MED221', 'Mark Gardner', 'Medicine');
INSERT INTO Lecturer VALUES ('ECON222', 'Jeffrey Myers', 'Economics');
INSERT INTO Lecturer VALUES ('GEOG223', 'Jeffery Thomas', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CENG224', 'Candice Fowler', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHAR225', 'Zachary Newton', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MSBM226', 'Jimmy Lewis', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('SOCI227', 'Elizabeth Velazquez', 'Sociology');
INSERT INTO Lecturer VALUES ('MED228', 'Angela Bowers', 'Medicine');
INSERT INTO Lecturer VALUES ('MATH229', 'Andrew Mckee', 'Mathematics');
INSERT INTO Lecturer VALUES ('MED230', 'Mark Moore', 'Medicine');
INSERT INTO Lecturer VALUES ('COMP231', 'Jesse Burns', 'Computing');
INSERT INTO Lecturer VALUES ('PHYS232', 'Amanda Bennett', 'Physics');
INSERT INTO Lecturer VALUES ('EENG233', 'Richard Rivera', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM234', 'Jennifer Williams', 'Chemistry');
INSERT INTO Lecturer VALUES ('CENG235', 'Nicholas Diaz', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MSBM236', 'Jonathan Ward', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CHEM237', 'Michael Meyer', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHYS238', 'Sean Edwards', 'Physics');
INSERT INTO Lecturer VALUES ('GEOG239', 'Nicole Woods', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG240', 'Lindsay Miller MD', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM241', 'Tyler Blackwell', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('EPNG242', 'Nicholas Wright', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('SOCI243', 'Benjamin Gilbert', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL244', 'Anne Torres', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHYS245', 'Jennifer Page', 'Physics');
INSERT INTO Lecturer VALUES ('CENG246', 'Laura Smith', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED247', 'Dylan Smith', 'Medicine');
INSERT INTO Lecturer VALUES ('EENG248', 'Aaron Nguyen', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MATH249', 'Tyler Brown', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHAR250', 'Isaac Caldwell', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CHEM251', 'Annette Parrish', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL252', 'Paul Lee', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CENG253', 'Nancy Parker', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL254', 'Johnathan Hutchinson', 'Biology');
INSERT INTO Lecturer VALUES ('EENG255', 'Barbara Cook', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MATH256', 'Deborah Trujillo', 'Mathematics');
INSERT INTO Lecturer VALUES ('BMNG257', 'Anthony Maldonado', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG258', 'Cody Levy', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GOVN259', 'Matthew Tanner', 'Government');
INSERT INTO Lecturer VALUES ('EPNG260', 'Amy Contreras', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EENG261', 'Allison Lewis', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CENG262', 'Christina Nguyen', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('SOCI263', 'Douglas King', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON264', 'Julie Osborne', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG265', 'Robyn Barnett', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BIOL266', 'Larry Collins', 'Biology');
INSERT INTO Lecturer VALUES ('EPNG267', 'Jesse Roberts', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('ECON268', 'David Roberts', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL269', 'Linda Burke', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CHEM270', 'Patricia Walker', 'Chemistry');
INSERT INTO Lecturer VALUES ('CENG271', 'Lauren Melendez', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('NURS272', 'Susan Gordon', 'Nursing');
INSERT INTO Lecturer VALUES ('PHYS273', 'Jordan Rivera', 'Physics');
INSERT INTO Lecturer VALUES ('CENG274', 'Kelsey Thomas', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BMNG275', 'Selena Bailey', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('COMP276', 'Lisa Hernandez', 'Computing');
INSERT INTO Lecturer VALUES ('MSBM277', 'Bradley Martin', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BMNG278', 'Mitchell Gibson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MSBM279', 'Kimberly Miller', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED280', 'Angela Joseph', 'Medicine');
INSERT INTO Lecturer VALUES ('MATH281', 'Jason Ford', 'Mathematics');
INSERT INTO Lecturer VALUES ('MED282', 'Joseph Winters', 'Medicine');
INSERT INTO Lecturer VALUES ('CENG283', 'Jeremy Stevens', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL284', 'Nathan Clark', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN285', 'Elizabeth Hamilton', 'Government');
INSERT INTO Lecturer VALUES ('EENG286', 'Jesse Dawson', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('MSBM287', 'Ryan Ross', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('GOVN288', 'Christopher Powell', 'Government');
INSERT INTO Lecturer VALUES ('COMP289', 'Mary Mcdowell', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL290', 'Hunter Wilson', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL291', 'Patrick Perkins DDS', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CENG292', 'Dan Foster', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('SOCI293', 'James Williams', 'Sociology');
INSERT INTO Lecturer VALUES ('GOVN294', 'Mark Escobar', 'Government');
INSERT INTO Lecturer VALUES ('CENG295', 'Timothy Miller', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED296', 'Sandra Marshall', 'Medicine');
INSERT INTO Lecturer VALUES ('MSBM297', 'Emily Li', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED298', 'Jeffrey Thompson', 'Medicine');
INSERT INTO Lecturer VALUES ('NURS299', 'Robert Ray', 'Nursing');
INSERT INTO Lecturer VALUES ('MSBM300', 'Brandy Hernandez', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL301', 'Hannah Lee', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CHEM302', 'Amber Wilson', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP303', 'Sean Escobar', 'Computing');
INSERT INTO Lecturer VALUES ('BIOL304', 'Leslie Griffin', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL305', 'Jay Thompson', 'Biology');
INSERT INTO Lecturer VALUES ('GEOG306', 'Peter Novak', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MSBM307', 'Samantha Rivera', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED308', 'Lisa Roth', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL309', 'John English', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MED310', 'Jamie Larson', 'Medicine');
INSERT INTO Lecturer VALUES ('CHEM311', 'Maria Sheppard', 'Chemistry');
INSERT INTO Lecturer VALUES ('NURS312', 'Paul Williams', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR313', 'James Crawford', 'Pharmacy');
INSERT INTO Lecturer VALUES ('BIOL314', 'Christina Wells', 'Biology');
INSERT INTO Lecturer VALUES ('EPNG315', 'Kellie Marshall', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS316', 'Taylor Thompson', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH317', 'Donna Matthews', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL318', 'Nicole Johnston', 'Biology');
INSERT INTO Lecturer VALUES ('GOVN319', 'Paula Hoffman', 'Government');
INSERT INTO Lecturer VALUES ('NURS320', 'Eric Faulkner', 'Nursing');
INSERT INTO Lecturer VALUES ('BMNG321', 'Jacob Jackson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EPNG322', 'Tina Griffin', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS323', 'Angela Ramirez', 'Nursing');
INSERT INTO Lecturer VALUES ('BIOL324', 'Kelly Taylor', 'Biology');
INSERT INTO Lecturer VALUES ('GEOG325', 'Teresa Haley', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG326', 'Destiny Welch', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG327', 'Molly Santos', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM328', 'Melody Tucker', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('COMP329', 'Jeffrey Scott', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG330', 'Amy Hansen', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PHYS331', 'Mark Hernandez', 'Physics');
INSERT INTO Lecturer VALUES ('PHAR332', 'Patrick Hanson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MATH333', 'David Ford', 'Mathematics');
INSERT INTO Lecturer VALUES ('BMNG334', 'Caleb Smith', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MATH335', 'Kelly Alexander', 'Mathematics');
INSERT INTO Lecturer VALUES ('PHYS336', 'Laura Jacobson', 'Physics');
INSERT INTO Lecturer VALUES ('EENG337', 'Brittany Harrington', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PSYC338', 'Lisa Campbell', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS339', 'Michael Mitchell', 'Nursing');
INSERT INTO Lecturer VALUES ('COMP340', 'Scott Lee', 'Computing');
INSERT INTO Lecturer VALUES ('NURS341', 'Amy Christensen', 'Nursing');
INSERT INTO Lecturer VALUES ('MSBM342', 'Paula Campos', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CENG343', 'Edward Rivera', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL344', 'Jesse Barton', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MSBM345', 'Melissa Hanna', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON346', 'Jennifer Barrett', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG347', 'Andrew Roth', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CENG348', 'Matthew Lyons', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL349', 'Lisa Orozco', 'Life Sciences');
INSERT INTO Lecturer VALUES ('COMP350', 'Nicole Watts', 'Computing');
INSERT INTO Lecturer VALUES ('EPNG351', 'Nathan Osborne', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('ECON352', 'Kimberly Taylor', 'Economics');
INSERT INTO Lecturer VALUES ('PHAR353', 'Amanda James', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PSYC354', 'Christian Peterson', 'Psychology');
INSERT INTO Lecturer VALUES ('EENG355', 'Todd Miller', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM356', 'Cameron Scott', 'Chemistry');
INSERT INTO Lecturer VALUES ('ECON357', 'John Bean MD', 'Economics');
INSERT INTO Lecturer VALUES ('MED358', 'April Wiley', 'Medicine');
INSERT INTO Lecturer VALUES ('SOCI359', 'Sandra Pierce', 'Sociology');
INSERT INTO Lecturer VALUES ('EPNG360', 'Marcus Navarro', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('NURS361', 'Autumn Coleman', 'Nursing');
INSERT INTO Lecturer VALUES ('SOCI362', 'Mrs. Becky Barker MD', 'Sociology');
INSERT INTO Lecturer VALUES ('EENG363', 'Linda Griffin', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('SOCI364', 'Micheal Hardin', 'Sociology');
INSERT INTO Lecturer VALUES ('GOVN365', 'Manuel Barnett', 'Government');
INSERT INTO Lecturer VALUES ('SOCI366', 'Robert Robinson', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS367', 'Thomas Murphy', 'Physics');
INSERT INTO Lecturer VALUES ('GOVN368', 'Tyler Russell', 'Government');
INSERT INTO Lecturer VALUES ('GEOG369', 'Paula Washington', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('CHEM370', 'Brian Romero', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL371', 'Amanda Roman', 'Biology');
INSERT INTO Lecturer VALUES ('CHEM372', 'Jessica Simmons', 'Chemistry');
INSERT INTO Lecturer VALUES ('BIOL373', 'Keith Torres', 'Biology');
INSERT INTO Lecturer VALUES ('PSYC374', 'Jacqueline Schroeder', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS375', 'Eric Weaver', 'Nursing');
INSERT INTO Lecturer VALUES ('NURS376', 'Anthony Fuller', 'Nursing');
INSERT INTO Lecturer VALUES ('PHAR377', 'Cheyenne Miller', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MATH378', 'Karen Moss', 'Mathematics');
INSERT INTO Lecturer VALUES ('EENG379', 'Christine Smith', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('ECON380', 'Todd Garcia', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG381', 'Kevin Nelson', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MATH382', 'Anne Andrews', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON383', 'Jon Russell', 'Economics');
INSERT INTO Lecturer VALUES ('GOVN384', 'Thomas Johnson', 'Government');
INSERT INTO Lecturer VALUES ('PSYC385', 'Marie Burns', 'Psychology');
INSERT INTO Lecturer VALUES ('GOVN386', 'Jason Campbell', 'Government');
INSERT INTO Lecturer VALUES ('MATH387', 'William Villa', 'Mathematics');
INSERT INTO Lecturer VALUES ('COMP388', 'Kevin Richardson', 'Computing');
INSERT INTO Lecturer VALUES ('PHYS389', 'Joseph Thomas', 'Physics');
INSERT INTO Lecturer VALUES ('GOVN390', 'Mark Smith', 'Government');
INSERT INTO Lecturer VALUES ('PHYS391', 'Laura Flores', 'Physics');
INSERT INTO Lecturer VALUES ('PHYS392', 'Matthew Martinez', 'Physics');
INSERT INTO Lecturer VALUES ('MED393', 'Melissa Perez', 'Medicine');
INSERT INTO Lecturer VALUES ('EENG394', 'Deborah Schaefer', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GOVN395', 'Destiny Gutierrez', 'Government');
INSERT INTO Lecturer VALUES ('BMNG396', 'Frank Romero', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CHEM397', 'Jared Yu', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH398', 'Charles Mitchell', 'Mathematics');
INSERT INTO Lecturer VALUES ('MSBM399', 'Douglas Barber', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PSYC400', 'Victoria Shepard', 'Psychology');
INSERT INTO Lecturer VALUES ('COMP401', 'Kristine Castillo', 'Computing');
INSERT INTO Lecturer VALUES ('EENG402', 'Cody Williams', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM403', 'Denise Charles', 'Chemistry');
INSERT INTO Lecturer VALUES ('EPNG404', 'Michael Carroll', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BMNG405', 'Andrew Campbell', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CHEM406', 'Brandy Smith', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHAR407', 'Ryan Wagner', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED408', 'Matthew Hall', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL409', 'Kimberly Martin', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL410', 'Steven Wong', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN411', 'Misty Smith', 'Government');
INSERT INTO Lecturer VALUES ('PHAR412', 'Jennifer Robinson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GOVN413', 'Jenny Moore', 'Government');
INSERT INTO Lecturer VALUES ('PHAR414', 'Ian Price', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI415', 'Samantha Carlson', 'Sociology');
INSERT INTO Lecturer VALUES ('BMNG416', 'Adam Ponce', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON417', 'Brian Sanchez', 'Economics');
INSERT INTO Lecturer VALUES ('CHEM418', 'Tracey Thompson', 'Chemistry');
INSERT INTO Lecturer VALUES ('GEOG419', 'Marc Melendez', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('ECON420', 'Monica Castillo', 'Economics');
INSERT INTO Lecturer VALUES ('COMP421', 'Darrell Woods', 'Computing');
INSERT INTO Lecturer VALUES ('CENG422', 'Susan Walsh', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CENG423', 'Colleen Morales', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GEOG424', 'Jeremy Dillon', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('ECON425', 'David Berry', 'Economics');
INSERT INTO Lecturer VALUES ('NURS426', 'Justin Jenkins', 'Nursing');
INSERT INTO Lecturer VALUES ('CENG427', 'Timothy Morgan', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHYS428', 'Kenneth Turner', 'Physics');
INSERT INTO Lecturer VALUES ('PHYS429', 'Tonya Watts', 'Physics');
INSERT INTO Lecturer VALUES ('CHEM430', 'Larry Moore', 'Chemistry');
INSERT INTO Lecturer VALUES ('EPNG431', 'Steven Chambers', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PHYS432', 'Richard Bailey', 'Physics');
INSERT INTO Lecturer VALUES ('MATH433', 'Joseph Ramos', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG434', 'Adam Rodriguez', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('NURS435', 'Jose Williams', 'Nursing');
INSERT INTO Lecturer VALUES ('EENG436', 'Jonathan Nichols', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL437', 'Matthew Bailey', 'Biology');
INSERT INTO Lecturer VALUES ('EENG438', 'Erin Perez', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('SOCI439', 'Gary Washington', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON440', 'Andrea Mcdowell', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC441', 'Glenda Weaver', 'Psychology');
INSERT INTO Lecturer VALUES ('MSBM442', 'Adam Moore', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BMNG443', 'Jonathan Grant', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CHEM444', 'Spencer Robinson', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHAR445', 'Julie Miller', 'Pharmacy');
INSERT INTO Lecturer VALUES ('ECON446', 'William Cherry', 'Economics');
INSERT INTO Lecturer VALUES ('BIOL447', 'Christian Brown', 'Biology');
INSERT INTO Lecturer VALUES ('NURS448', 'Kristi Burton', 'Nursing');
INSERT INTO Lecturer VALUES ('GEOG449', 'Renee Hunter', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BMNG450', 'Teresa Montoya', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHYS451', 'Angela Hughes', 'Physics');
INSERT INTO Lecturer VALUES ('CENG452', 'Russell Mills', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GOVN453', 'Michael Miller', 'Government');
INSERT INTO Lecturer VALUES ('CENG454', 'Mr. Robert Harding', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('EPNG455', 'Sarah Cortez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('PSYC456', 'Thomas Ingram', 'Psychology');
INSERT INTO Lecturer VALUES ('PSYC457', 'Linda Cooper', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS458', 'Jeffrey Brown', 'Nursing');
INSERT INTO Lecturer VALUES ('CHEM459', 'Nicole Hernandez', 'Chemistry');
INSERT INTO Lecturer VALUES ('EPNG460', 'Sierra Benton', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('CENG461', 'Eddie Zuniga', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PSYC462', 'Jessica Arellano', 'Psychology');
INSERT INTO Lecturer VALUES ('PHAR463', 'Deborah Goodwin', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MSBM464', 'Jeremy Lucas', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL465', 'Elizabeth Riggs', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PHAR466', 'George Nelson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('COMP467', 'Trevor Berry', 'Computing');
INSERT INTO Lecturer VALUES ('EENG468', 'Zachary Mckee', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM469', 'Robert Edwards', 'Chemistry');
INSERT INTO Lecturer VALUES ('EPNG470', 'Tammy Wilson', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EENG471', 'Jacob Gilbert', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('ECON472', 'Richard George', 'Economics');
INSERT INTO Lecturer VALUES ('EPNG473', 'Thomas Eaton', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('SOCI474', 'Ashley Higgins', 'Sociology');
INSERT INTO Lecturer VALUES ('MSBM475', 'Jacob Swanson', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('CENG476', 'Kelly Bird', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PHAR477', 'Jonathan Morris', 'Pharmacy');
INSERT INTO Lecturer VALUES ('CHEM478', 'Jon Schmidt', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHYS479', 'Mrs. Crystal Douglas', 'Physics');
INSERT INTO Lecturer VALUES ('CENG480', 'Heidi Wagner', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL481', 'Robert Santana', 'Biology');
INSERT INTO Lecturer VALUES ('MED482', 'Daniel Valdez', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL483', 'Dale Lam', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MSBM484', 'Timothy Fischer', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BIOL485', 'Laura Mendoza', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL486', 'Stephanie Walker', 'Life Sciences');
INSERT INTO Lecturer VALUES ('BIOL487', 'Ronald Reed', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN488', 'Gloria Trujillo', 'Government');
INSERT INTO Lecturer VALUES ('MATH489', 'Guy Allen', 'Mathematics');
INSERT INTO Lecturer VALUES ('GOVN490', 'Brittany Williams', 'Government');
INSERT INTO Lecturer VALUES ('CENG491', 'Lindsey Martinez', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BMNG492', 'Anthony Valenzuela', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('EENG493', 'Caitlin Thomas', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR494', 'Erika Chavez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('SOCI495', 'Jonathan Chen', 'Sociology');
INSERT INTO Lecturer VALUES ('CHEM496', 'Mr. Thomas Oconnor', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH497', 'Rebecca Schmidt', 'Mathematics');
INSERT INTO Lecturer VALUES ('MSBM498', 'Daniel Watts', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('GEOG499', 'Robert Jackson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('PSYC500', 'Peter Lopez', 'Psychology');
INSERT INTO Lecturer VALUES ('BIOL501', 'Charlotte Blake', 'Biology');
INSERT INTO Lecturer VALUES ('CENG502', 'Jessica Alexander', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED503', 'Holly Brown', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC504', 'Sergio Vincent', 'Psychology');
INSERT INTO Lecturer VALUES ('CENG505', 'Sarah Taylor', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CENG506', 'David Smith', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MATH507', 'Lisa Hobbs', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL508', 'Kent Jimenez', 'Life Sciences');
INSERT INTO Lecturer VALUES ('ECON509', 'Heidi Gutierrez', 'Economics');
INSERT INTO Lecturer VALUES ('EENG510', 'Fernando Jones', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('COMP511', 'Lawrence Santos', 'Computing');
INSERT INTO Lecturer VALUES ('MED512', 'Anne Cole', 'Medicine');
INSERT INTO Lecturer VALUES ('MED513', 'Mathew Rubio', 'Medicine');
INSERT INTO Lecturer VALUES ('GEOG514', 'Adam Holt', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MSBM515', 'Jacob Reynolds', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('EPNG516', 'Anthony Osborne', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('EPNG517', 'Elizabeth Castaneda', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GEOG518', 'David Cole', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('SOCI519', 'Donald Lawson MD', 'Sociology');
INSERT INTO Lecturer VALUES ('BMNG520', 'Emily Mays', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL521', 'Isabella Lynch', 'Biology');
INSERT INTO Lecturer VALUES ('MATH522', 'Edward Garcia', 'Mathematics');
INSERT INTO Lecturer VALUES ('MSBM523', 'Susan Green', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('PHAR524', 'Becky Mendez', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MED525', 'Julie Moore', 'Medicine');
INSERT INTO Lecturer VALUES ('NURS526', 'Joshua Brown', 'Nursing');
INSERT INTO Lecturer VALUES ('ECON527', 'Jonathan Jones', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG528', 'Paul Flores', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CHEM529', 'Preston Allen', 'Chemistry');
INSERT INTO Lecturer VALUES ('BMNG530', 'Julie Miranda', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON531', 'Drew Ryan', 'Economics');
INSERT INTO Lecturer VALUES ('PHAR532', 'Desiree Anderson', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MATH533', 'Belinda Roy', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON534', 'Jeffrey Garcia', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG535', 'Gary Nguyen', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GOVN536', 'Russell Kelly', 'Government');
INSERT INTO Lecturer VALUES ('GOVN537', 'Tammy Arnold', 'Government');
INSERT INTO Lecturer VALUES ('PHAR538', 'Michael Yates', 'Pharmacy');
INSERT INTO Lecturer VALUES ('ECON539', 'Colin Ayers', 'Economics');
INSERT INTO Lecturer VALUES ('GOVN540', 'Christopher Schwartz', 'Government');
INSERT INTO Lecturer VALUES ('BIOL541', 'Julie Lowe', 'Biology');
INSERT INTO Lecturer VALUES ('EENG542', 'Victoria Phillips', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('CHEM543', 'Levi Chandler', 'Chemistry');
INSERT INTO Lecturer VALUES ('COMP544', 'Elizabeth Martin', 'Computing');
INSERT INTO Lecturer VALUES ('MED545', 'Tiffany Perez', 'Medicine');
INSERT INTO Lecturer VALUES ('SOCI546', 'Ashley Koch', 'Sociology');
INSERT INTO Lecturer VALUES ('SOCI547', 'Martin Taylor', 'Sociology');
INSERT INTO Lecturer VALUES ('PHAR548', 'Matthew Cross', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MSBM549', 'Jennifer Stafford MD', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON550', 'Kristen Jordan', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG551', 'Erica James', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL552', 'Victor Patton', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN553', 'Dan Clark', 'Government');
INSERT INTO Lecturer VALUES ('COMP554', 'Kristen Atkins PhD', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG555', 'Cynthia Long', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL556', 'Neil Blackwell', 'Biology');
INSERT INTO Lecturer VALUES ('CENG557', 'Richard Johnson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CHEM558', 'Karen Davis', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHAR559', 'Daniel Petty', 'Pharmacy');
INSERT INTO Lecturer VALUES ('GEOG560', 'William Gonzalez', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('EPNG561', 'Dr. Alex Palmer', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('SOCI562', 'Joshua Welch', 'Sociology');
INSERT INTO Lecturer VALUES ('SOCI563', 'Susan Smith', 'Sociology');
INSERT INTO Lecturer VALUES ('MATH564', 'George Fowler', 'Mathematics');
INSERT INTO Lecturer VALUES ('ECON565', 'Dr. Karen Smith', 'Economics');
INSERT INTO Lecturer VALUES ('BMNG566', 'Amy Miller', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('ECON567', 'Nicole Riggs MD', 'Economics');
INSERT INTO Lecturer VALUES ('CHEM568', 'Wayne Walker', 'Chemistry');
INSERT INTO Lecturer VALUES ('PHAR569', 'Janet Bates', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PSYC570', 'Stephanie Simon', 'Psychology');
INSERT INTO Lecturer VALUES ('PHYS571', 'Michael Mueller', 'Physics');
INSERT INTO Lecturer VALUES ('PHYS572', 'Damon Rodriguez', 'Physics');
INSERT INTO Lecturer VALUES ('EPNG573', 'Kim Carpenter', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('BIOL574', 'James Bryant', 'Biology');
INSERT INTO Lecturer VALUES ('BMNG575', 'Laura King', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PSYC576', 'Gregory Ryan', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI577', 'Jennifer Roberts', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS578', 'Alexander Johnson', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC579', 'Darryl Barnes', 'Psychology');
INSERT INTO Lecturer VALUES ('EENG580', 'Ashley Campbell', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('ECON581', 'Alexandria Hickman', 'Economics');
INSERT INTO Lecturer VALUES ('GOVN582', 'Randy Durham', 'Government');
INSERT INTO Lecturer VALUES ('CHEM583', 'Christopher Bennett', 'Chemistry');
INSERT INTO Lecturer VALUES ('SOCI584', 'Rebecca James', 'Sociology');
INSERT INTO Lecturer VALUES ('ECON585', 'Margaret Flores', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC586', 'Nicole Blackburn', 'Psychology');
INSERT INTO Lecturer VALUES ('COMP587', 'John Berg', 'Computing');
INSERT INTO Lecturer VALUES ('MED588', 'Robert Taylor', 'Medicine');
INSERT INTO Lecturer VALUES ('SOCI589', 'Jesse Arroyo', 'Sociology');
INSERT INTO Lecturer VALUES ('COMP590', 'Eric Figueroa', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR591', 'Joy Valenzuela', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EENG592', 'Joshua Melton', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EENG593', 'Jacob Kirk', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('COMP594', 'Lisa Mcgee', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG595', 'Morgan Rice', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH596', 'Robert Stokes', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL597', 'Bryan Weeks', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EENG598', 'John Peters', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHYS599', 'Tyler Long', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL600', 'Katherine Fisher', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CENG601', 'Scott Malone', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GEOG602', 'Virginia Anderson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BMNG603', 'Sheryl Ruiz', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL604', 'Sarah Larsen', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN605', 'Andrea Paul', 'Government');
INSERT INTO Lecturer VALUES ('SOCI606', 'Sean Rodgers', 'Sociology');
INSERT INTO Lecturer VALUES ('GOVN607', 'Joseph Hall', 'Government');
INSERT INTO Lecturer VALUES ('NURS608', 'Matthew Sloan', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC609', 'Holly Brown', 'Psychology');
INSERT INTO Lecturer VALUES ('EPNG610', 'Karla Lopez', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MSBM611', 'Sherri Keller', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('ECON612', 'Joshua Wagner', 'Economics');
INSERT INTO Lecturer VALUES ('SOCI613', 'Regina Cruz', 'Sociology');
INSERT INTO Lecturer VALUES ('MED614', 'Jamie Horton', 'Medicine');
INSERT INTO Lecturer VALUES ('PSYC615', 'Jennifer Rodriguez', 'Psychology');
INSERT INTO Lecturer VALUES ('CENG616', 'Roy Jones', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('COMP617', 'Nicole Arnold', 'Computing');
INSERT INTO Lecturer VALUES ('EENG618', 'Julie Williams DVM', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('EPNG619', 'Emily Bass', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('MED620', 'Derrick Cain', 'Medicine');
INSERT INTO Lecturer VALUES ('MED621', 'Jason Johnson', 'Medicine');
INSERT INTO Lecturer VALUES ('CENG622', 'Jason Schmidt', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GOVN623', 'Brittney Hahn', 'Government');
INSERT INTO Lecturer VALUES ('COMP624', 'Robert Torres', 'Computing');
INSERT INTO Lecturer VALUES ('MSBM625', 'Kyle Jordan', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BMNG626', 'Ronald Rodriguez', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CENG627', 'Danielle Barnes', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL628', 'Shawn Warren', 'Biology');
INSERT INTO Lecturer VALUES ('SOCI629', 'Michelle Baker', 'Sociology');
INSERT INTO Lecturer VALUES ('PHYS630', 'Cody Jordan', 'Physics');
INSERT INTO Lecturer VALUES ('CENG631', 'Cody Giles', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('MED632', 'Cristian Gardner', 'Medicine');
INSERT INTO Lecturer VALUES ('EENG633', 'Alice Hogan', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL634', 'Shawn Martin', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GEOG635', 'Henry Parsons', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL636', 'Sandra Russo', 'Biology');
INSERT INTO Lecturer VALUES ('CENG637', 'Diamond Gibson', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('BIOL638', 'Jessica Jackson', 'Biology');
INSERT INTO Lecturer VALUES ('BIOL639', 'Jessica Leonard', 'Life Sciences');
INSERT INTO Lecturer VALUES ('SOCI640', 'Troy Mcintosh', 'Sociology');
INSERT INTO Lecturer VALUES ('GOVN641', 'Mr. Matthew Dennis', 'Government');
INSERT INTO Lecturer VALUES ('GOVN642', 'Morgan Larsen', 'Government');
INSERT INTO Lecturer VALUES ('BIOL643', 'Gregory Mclaughlin', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MATH644', 'Kimberly Henson', 'Mathematics');
INSERT INTO Lecturer VALUES ('SOCI645', 'Robert York', 'Sociology');
INSERT INTO Lecturer VALUES ('PSYC646', 'Peter Williams', 'Psychology');
INSERT INTO Lecturer VALUES ('MSBM647', 'Heather Rodriguez', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('MED648', 'Joshua Wilkins', 'Medicine');
INSERT INTO Lecturer VALUES ('BIOL649', 'Mark Castaneda', 'Biology');
INSERT INTO Lecturer VALUES ('PHYS650', 'Patrick Thomas', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM651', 'Mr. Martin Bowen MD', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('COMP652', 'Amber Craig', 'Computing');
INSERT INTO Lecturer VALUES ('NURS653', 'Amber Morton', 'Nursing');
INSERT INTO Lecturer VALUES ('BMNG654', 'Bryan Allen Jr.', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GOVN655', 'Michelle Davidson', 'Government');
INSERT INTO Lecturer VALUES ('EENG656', 'Heather Hodges', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL657', 'Michael Wheeler', 'Life Sciences');
INSERT INTO Lecturer VALUES ('PSYC658', 'Brandi Morales', 'Psychology');
INSERT INTO Lecturer VALUES ('MATH659', 'Aaron Pitts Jr.', 'Mathematics');
INSERT INTO Lecturer VALUES ('GEOG660', 'Vincent Burns', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GEOG661', 'Kelsey Lyons', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('GOVN662', 'Rebecca Ortiz', 'Government');
INSERT INTO Lecturer VALUES ('SOCI663', 'Emily Thomas', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL664', 'Jennifer Kim', 'Life Sciences');
INSERT INTO Lecturer VALUES ('ECON665', 'Charles Hansen', 'Economics');
INSERT INTO Lecturer VALUES ('PSYC666', 'Elizabeth Gonzalez', 'Psychology');
INSERT INTO Lecturer VALUES ('PSYC667', 'Mark Miller', 'Psychology');
INSERT INTO Lecturer VALUES ('SOCI668', 'Megan Rodriguez', 'Sociology');
INSERT INTO Lecturer VALUES ('BIOL669', 'Brett Ferguson DDS', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EPNG670', 'Glenn Keller', 'Electrical Power Engineering');
INSERT INTO Lecturer VALUES ('GOVN671', 'Brenda Cortez', 'Government');
INSERT INTO Lecturer VALUES ('COMP672', 'Cindy Fox', 'Computing');
INSERT INTO Lecturer VALUES ('NURS673', 'David Medina', 'Nursing');
INSERT INTO Lecturer VALUES ('ECON674', 'Ronnie Castro', 'Economics');
INSERT INTO Lecturer VALUES ('SOCI675', 'Craig Murphy', 'Sociology');
INSERT INTO Lecturer VALUES ('NURS676', 'Amanda Spencer', 'Nursing');
INSERT INTO Lecturer VALUES ('MATH677', 'Jose Bates', 'Mathematics');
INSERT INTO Lecturer VALUES ('MATH678', 'Austin Davidson', 'Mathematics');
INSERT INTO Lecturer VALUES ('BIOL679', 'Austin Blake', 'Biology');
INSERT INTO Lecturer VALUES ('EENG680', 'Courtney Reed', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('PHAR681', 'Mr. Marc Short', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PSYC682', 'Tiffany Bray', 'Psychology');
INSERT INTO Lecturer VALUES ('GEOG683', 'Larry Burns', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL684', 'Katrina Cervantes', 'Life Sciences');
INSERT INTO Lecturer VALUES ('MATH685', 'Joe Wolf', 'Mathematics');
INSERT INTO Lecturer VALUES ('BMNG686', 'Tami Phillips', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BIOL687', 'Brian Brown', 'Biology');
INSERT INTO Lecturer VALUES ('MATH688', 'John Martinez', 'Mathematics');
INSERT INTO Lecturer VALUES ('BMNG689', 'Kathleen Green', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('CENG690', 'Tracy Walsh', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CENG691', 'John Garcia', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('EENG692', 'Kimberly Torres', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GEOG693', 'Melissa Keith', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('SOCI694', 'Mark Cole', 'Sociology');
INSERT INTO Lecturer VALUES ('SOCI695', 'Jacqueline Roberts', 'Sociology');
INSERT INTO Lecturer VALUES ('PHAR696', 'Adam Berry', 'Pharmacy');
INSERT INTO Lecturer VALUES ('EENG697', 'Laura Young', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('BIOL698', 'James Cooper', 'Life Sciences');
INSERT INTO Lecturer VALUES ('CENG699', 'Mr. Gabriel Conley MD', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('PSYC700', 'Gregory George', 'Psychology');
INSERT INTO Lecturer VALUES ('NURS701', 'Michelle Jones', 'Nursing');
INSERT INTO Lecturer VALUES ('PSYC702', 'Nicole Harrison', 'Psychology');
INSERT INTO Lecturer VALUES ('CHEM703', 'Michael Lopez', 'Chemistry');
INSERT INTO Lecturer VALUES ('EENG704', 'Deborah Alvarez', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('COMP705', 'Gregory Long', 'Computing');
INSERT INTO Lecturer VALUES ('NURS706', 'Jacob Avila', 'Nursing');
INSERT INTO Lecturer VALUES ('MED707', 'Natalie Miller', 'Medicine');
INSERT INTO Lecturer VALUES ('PHAR708', 'Michael Taylor', 'Pharmacy');
INSERT INTO Lecturer VALUES ('PHAR709', 'Kimberly Taylor', 'Pharmacy');
INSERT INTO Lecturer VALUES ('MATH710', 'Jose Ball', 'Mathematics');
INSERT INTO Lecturer VALUES ('CENG711', 'Jennifer Thomas', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('GEOG712', 'Tracy Williams', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL713', 'Emily Garcia', 'Biology');
INSERT INTO Lecturer VALUES ('CHEM714', 'Gary Roberts', 'Chemistry');
INSERT INTO Lecturer VALUES ('NURS715', 'Luke Huber', 'Nursing');
INSERT INTO Lecturer VALUES ('CENG716', 'William Sullivan', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('COMP717', 'Kevin Pierce', 'Computing');
INSERT INTO Lecturer VALUES ('PHAR718', 'Todd Perry', 'Pharmacy');
INSERT INTO Lecturer VALUES ('NURS719', 'Steven Peterson', 'Nursing');
INSERT INTO Lecturer VALUES ('BMNG720', 'Todd Farmer', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('GEOG721', 'Allison Cox', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MATH722', 'Michelle Taylor', 'Mathematics');
INSERT INTO Lecturer VALUES ('CENG723', 'Vincent Russell', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CHEM724', 'Kristen Ross', 'Chemistry');
INSERT INTO Lecturer VALUES ('BMNG725', 'Timothy Daugherty', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG726', 'Andrea Hancock', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('BMNG727', 'Michael Frye', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('MATH728', 'Dave Fletcher', 'Mathematics');
INSERT INTO Lecturer VALUES ('PSYC729', 'Claudia Duncan', 'Psychology');
INSERT INTO Lecturer VALUES ('BMNG730', 'Dana Baker MD', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PSYC731', 'Lauren Austin', 'Psychology');
INSERT INTO Lecturer VALUES ('CENG732', 'Hunter Porter', 'Civil Engineering');
INSERT INTO Lecturer VALUES ('CHEM733', 'Ronald Hughes', 'Chemistry');
INSERT INTO Lecturer VALUES ('MATH734', 'Robert Long', 'Mathematics');
INSERT INTO Lecturer VALUES ('COMP735', 'Albert Jackson', 'Computing');
INSERT INTO Lecturer VALUES ('GEOG736', 'Mark Ortega MD', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('MED737', 'James Finley', 'Medicine');
INSERT INTO Lecturer VALUES ('PHYS738', 'Beth Martinez', 'Physics');
INSERT INTO Lecturer VALUES ('MSBM739', 'Evan Reed', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('GEOG740', 'Mary Patterson', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('COMP741', 'Carl Turner', 'Computing');
INSERT INTO Lecturer VALUES ('MSBM742', 'Sandra Hill', 'Mona School of Business & Management');
INSERT INTO Lecturer VALUES ('BMNG743', 'Tara Compton', 'Biomedical Engineering');
INSERT INTO Lecturer VALUES ('PHYS744', 'Thomas Daniels', 'Physics');
INSERT INTO Lecturer VALUES ('BIOL745', 'Nicole Martinez', 'Life Sciences');
INSERT INTO Lecturer VALUES ('EENG746', 'Jennifer Chandler', 'Electronics Engineering');
INSERT INTO Lecturer VALUES ('GEOG747', 'Michelle Owen MD', 'Geography & Geology');
INSERT INTO Lecturer VALUES ('BIOL748', 'Christina Brown', 'Life Sciences');
INSERT INTO Lecturer VALUES ('GOVN749', 'Jessica Nguyen', 'Government');
INSERT INTO Lecturer VALUES ('COMP750', 'Mark Diaz', 'Computing');

